#include "area_id.hpp"

#include <unordered_map>

AreaID NameToAreaID(const std::string& name)
{
    static std::unordered_map<std::string, AreaID> nameAreaMap = {
        {"NONE", AreaID::NONE},
        {"Root", AreaID::Root},
        {"Root Exits", AreaID::RootExits},
        {"Child Spawn", AreaID::ChildSpawn},
        {"Adult Spawn", AreaID::AdultSpawn},
        {"Prelude of Light Warp", AreaID::PreludeOfLightWarp},
        {"Minuet of Forest Warp", AreaID::MinuetOfForestWarp},
        {"Bolero of Fire Warp", AreaID::BoleroOfFireWarp},
        {"Serenade of Water Warp", AreaID::SerenadeOfWaterWarp},
        {"Requiem of Spirit Warp", AreaID::RequiemOfSpiritWarp},
        {"Nocturne of Shadow Warp", AreaID::NocturneOfShadowWarp},
        {"Kokiri Forest", AreaID::KokiriForest},
        {"KF Outside Deku Tree", AreaID::KFOutsideDekuTree},
        {"KF Links House", AreaID::KFLinksHouse},
        {"KF Midos House", AreaID::KFMidosHouse},
        {"KF Sarias House", AreaID::KFSariasHouse},
        {"KF House of Twins", AreaID::KFHouseOfTwins},
        {"KF Know It All House", AreaID::KFKnowItAllHouse},
        {"KF Kokiri Shop", AreaID::KFKokiriShop},
        {"LW Forest Exit", AreaID::LWForestExit},
        {"Lost Woods", AreaID::LostWoods},
        {"LW Beyond Mido", AreaID::LWBeyondMido},
        {"Lost Woods Mushroom Timeout", AreaID::LostWoodsMushroomTimeout},
        {"SFM Entryway", AreaID::SFMEntryway},
        {"Sacred Forest Meadow", AreaID::SacredForestMeadow},
        {"SFM Forest Temple Entrance Ledge", AreaID::SFMForestTempleEntranceLedge},
        {"LW Bridge From Forest", AreaID::LWBridgeFromForest},
        {"LW Bridge", AreaID::LWBridge},
        {"Hyrule Field", AreaID::HyruleField},
        {"Lake Hylia", AreaID::LakeHylia},
        {"LH Fishing Island", AreaID::LHFishingIsland},
        {"LH Owl Flight", AreaID::LHOwlFlight},
        {"LH Lab", AreaID::LHLab},
        {"LH Fishing Hole", AreaID::LHFishingHole},
        {"Gerudo Valley", AreaID::GerudoValley},
        {"GV Upper Stream", AreaID::GVUpperStream},
        {"GV Lower Stream", AreaID::GVLowerStream},
        {"GV Grotto Ledge", AreaID::GVGrottoLedge},
        {"GV Crate Ledge", AreaID::GVCrateLedge},
        {"GV Fortress Side", AreaID::GVFortressSide},
        {"GV Carpenter Tent", AreaID::GVCarpenterTent},
        {"Gerudo Fortress", AreaID::GerudoFortress},
        {"GF Outside Gate", AreaID::GFOutsideGate},
        {"Wasteland Near Fortress", AreaID::WastelandNearFortress},
        {"Haunted Wasteland", AreaID::HauntedWasteland},
        {"Wasteland Near Colossus", AreaID::WastelandNearColossus},
        {"Desert Colossus", AreaID::DesertColossus},
        {"Desert Colossus From Spirit Lobby", AreaID::DesertColossusFromSpiritLobby},
        {"Colossus Great Fairy Fountain", AreaID::ColossusGreatFairyFountain},
        {"Market Entrance", AreaID::MarketEntrance},
        {"Market", AreaID::Market},
        {"Market Back Alley", AreaID::MarketBackAlley},
        {"ToT Entrance", AreaID::ToTEntrance},
        {"Temple of Time", AreaID::TempleOfTime},
        {"Beyond Door of Time", AreaID::BeyondDoorOfTime},
        {"Castle Grounds", AreaID::CastleGrounds},
        {"Hyrule Castle Grounds", AreaID::HyruleCastleGrounds},
        {"HC Garden", AreaID::HCGarden},
        {"HC Garden Locations", AreaID::HCGardenLocations},
        {"HC Great Fairy Fountain", AreaID::HCGreatFairyFountain},
        {"Ganons Castle Grounds", AreaID::GanonsCastleGrounds},
        {"OGC Great Fairy Fountain", AreaID::OGCGreatFairyFountain},
        {"Market Guard House", AreaID::MarketGuardHouse},
        {"Market Bazaar", AreaID::MarketBazaar},
        {"Market Mask Shop", AreaID::MarketMaskShop},
        {"Market Shooting Gallery", AreaID::MarketShootingGallery},
        {"Market Bombchu Bowling", AreaID::MarketBombchuBowling},
        {"Market Potion Shop", AreaID::MarketPotionShop},
        {"Market Treasure Chest Game", AreaID::MarketTreasureChestGame},
        {"Market Bombchu Shop", AreaID::MarketBombchuShop},
        {"Market Dog Lady House", AreaID::MarketDogLadyHouse},
        {"Market Man in Green House", AreaID::MarketManInGreenHouse},
        {"Kakariko Village", AreaID::KakarikoVillage},
        {"Kak Impas Ledge", AreaID::KakImpasLedge},
        {"Kak Impas Rooftop", AreaID::KakImpasRooftop},
        {"Kak Odd Medicine Rooftop", AreaID::KakOddMedicineRooftop},
        {"Kak Backyard", AreaID::KakBackyard},
        {"Kak Carpenter Boss House", AreaID::KakCarpenterBossHouse},
        {"Kak House of Skulltula", AreaID::KakHouseOfSkulltula},
        {"Kak Impas House", AreaID::KakImpasHouse},
        {"Kak Impas House Back", AreaID::KakImpasHouseBack},
        {"Kak Impas House Near Cow", AreaID::KakImpasHouseNearCow},
        {"Kak Windmill", AreaID::KakWindmill},
        {"Kak Bazaar", AreaID::KakBazaar},
        {"Kak Shooting Gallery", AreaID::KakShootingGallery},
        {"Kak Potion Shop Front", AreaID::KakPotionShopFront},
        {"Kak Potion Shop Back", AreaID::KakPotionShopBack},
        {"Kak Odd Medicine Building", AreaID::KakOddMedicineBuilding},
        {"Graveyard", AreaID::Graveyard},
        {"Graveyard Shield Grave", AreaID::GraveyardShieldGrave},
        {"Graveyard Heart Piece Grave", AreaID::GraveyardHeartPieceGrave},
        {"Graveyard Royal Familys Tomb", AreaID::GraveyardRoyalFamilysTomb},
        {"Graveyard Dampes Grave", AreaID::GraveyardDampesGrave},
        {"Graveyard Dampes House", AreaID::GraveyardDampesHouse},
        {"Graveyard Warp Pad Region", AreaID::GraveyardWarpPadRegion},
        {"Kak Behind Gate", AreaID::KakBehindGate},
        {"Death Mountain", AreaID::DeathMountain},
        {"Death Mountain Summit", AreaID::DeathMountainSummit},
        {"DMT Owl Flight", AreaID::DMTOwlFlight},
        {"Goron City", AreaID::GoronCity},
        {"GC Woods Warp", AreaID::GCWoodsWarp},
        {"GC Darunias Chamber", AreaID::GCDaruniasChamber},
        {"GC Grotto Platform", AreaID::GCGrottoPlatform},
        {"GC Shop", AreaID::GCShop},
        {"DMC Upper Nearby", AreaID::DMCUpperNearby},
        {"DMC Upper Local", AreaID::DMCUpperLocal},
        {"DMC Ladder Area Nearby", AreaID::DMCLadderAreaNearby},
        {"DMC Lower Nearby", AreaID::DMCLowerNearby},
        {"DMC Lower Local", AreaID::DMCLowerLocal},
        {"DMC Central Nearby", AreaID::DMCCentralNearby},
        {"DMC Central Local", AreaID::DMCCentralLocal},
        {"DMC Fire Temple Entrance", AreaID::DMCFireTempleEntrance},
        {"DMC Great Fairy Fountain", AreaID::DMCGreatFairyFountain},
        {"DMT Great Fairy Fountain", AreaID::DMTGreatFairyFountain},
        {"ZR Front", AreaID::ZRFront},
        {"Zora River", AreaID::ZoraRiver},
        {"ZR Behind Waterfall", AreaID::ZRBehindWaterfall},
        {"ZR Top of Waterfall", AreaID::ZRTopOfWaterfall},
        {"Zoras Domain", AreaID::ZorasDomain},
        {"ZD Behind King Zora", AreaID::ZDBehindKingZora},
        {"ZD Eyeball Frog Timeout", AreaID::ZDEyeballFrogTimeout},
        {"Zoras Fountain", AreaID::ZorasFountain},
        {"ZF Ice Ledge", AreaID::ZFIceLedge},
        {"ZD Shop", AreaID::ZDShop},
        {"ZF Great Fairy Fountain", AreaID::ZFGreatFairyFountain},
        {"Lon Lon Ranch", AreaID::LonLonRanch},
        {"LLR Talons House", AreaID::LLRTalonsHouse},
        {"LLR Stables", AreaID::LLRStables},
        {"LLR Tower", AreaID::LLRTower},
        {"Ganons Castle Tower", AreaID::GanonsCastleTower},
        {"GF Storms Grotto", AreaID::GFStormsGrotto},
        {"ZD Storms Grotto", AreaID::ZDStormsGrotto},
        {"KF Storms Grotto", AreaID::KFStormsGrotto},
        {"LW Near Shortcuts Grotto", AreaID::LWNearShortcutsGrotto},
        {"Deku Theater", AreaID::DekuTheater},
        {"LW Scrubs Grotto", AreaID::LWScrubsGrotto},
        {"SFM Fairy Grotto", AreaID::SFMFairyGrotto},
        {"SFM Storms Grotto", AreaID::SFMStormsGrotto},
        {"SFM Wolfos Grotto", AreaID::SFMWolfosGrotto},
        {"LLR Grotto", AreaID::LLRGrotto},
        {"HF Southeast Grotto", AreaID::HFSoutheastGrotto},
        {"HF Open Grotto", AreaID::HFOpenGrotto},
        {"HF Inside Fence Grotto", AreaID::HFInsideFenceGrotto},
        {"HF Cow Grotto", AreaID::HFCowGrotto},
        {"HF Near Market Grotto", AreaID::HFNearMarketGrotto},
        {"HF Fairy Grotto", AreaID::HFFairyGrotto},
        {"HF Near Kak Grotto", AreaID::HFNearKakGrotto},
        {"HF Tektite Grotto", AreaID::HFTektiteGrotto},
        {"HC Storms Grotto", AreaID::HCStormsGrotto},
        {"Kak Redead Grotto", AreaID::KakRedeadGrotto},
        {"Kak Open Grotto", AreaID::KakOpenGrotto},
        {"DMT Cow Grotto", AreaID::DMTCowGrotto},
        {"DMT Storms Grotto", AreaID::DMTStormsGrotto},
        {"GC Grotto", AreaID::GCGrotto},
        {"DMC Upper Grotto", AreaID::DMCUpperGrotto},
        {"DMC Hammer Grotto", AreaID::DMCHammerGrotto},
        {"ZR Open Grotto", AreaID::ZROpenGrotto},
        {"ZR Fairy Grotto", AreaID::ZRFairyGrotto},
        {"ZR Storms Grotto", AreaID::ZRStormsGrotto},
        {"LH Grotto", AreaID::LHGrotto},
        {"Colossus Grotto", AreaID::ColossusGrotto},
        {"GV Octorok Grotto", AreaID::GVOctorokGrotto},
        {"GV Storms Grotto", AreaID::GVStormsGrotto},
        {"Deku Tree Lobby", AreaID::DekuTreeLobby},
        {"Dodongos Cavern Beginning", AreaID::DodongosCavernBeginning},
        {"Jabu Jabus Belly Beginning", AreaID::JabuJabusBellyBeginning},
        {"Forest Temple Lobby", AreaID::ForestTempleLobby},
        {"Fire Temple Lower", AreaID::FireTempleLower},
        {"Water Temple Lobby", AreaID::WaterTempleLobby},
        {"Spirit Temple Lobby", AreaID::SpiritTempleLobby},
        {"Shadow Temple Entryway", AreaID::ShadowTempleEntryway},
        {"Ice Cavern Beginning", AreaID::IceCavernBeginning},
        {"Bottom of the Well", AreaID::BottomOfTheWell},
        {"Gerudo Training Ground Lobby", AreaID::GerudoTrainingGroundLobby},
        {"Ganons Castle Lobby", AreaID::GanonsCastleLobby},
    };

    if (nameAreaMap.count(name) > 0)
    {
        return nameAreaMap.at(name);
    }
    return AreaID::INVALID;
}

std::string AreaIDToName(const AreaID& areaId)
{
    static std::unordered_map<AreaID, std::string> areaNameMap = {
        {AreaID::NONE, "NONE"},
        {AreaID::Root, "Root"},
        {AreaID::RootExits, "Root Exits"},
        {AreaID::ChildSpawn, "Child Spawn"},
        {AreaID::AdultSpawn, "Adult Spawn"},
        {AreaID::PreludeOfLightWarp, "Prelude of Light Warp"},
        {AreaID::MinuetOfForestWarp, "Minuet of Forest Warp"},
        {AreaID::BoleroOfFireWarp, "Bolero of Fire Warp"},
        {AreaID::SerenadeOfWaterWarp, "Serenade of Water Warp"},
        {AreaID::RequiemOfSpiritWarp, "Requiem of Spirit Warp"},
        {AreaID::NocturneOfShadowWarp, "Nocturne of Shadow Warp"},
        {AreaID::KokiriForest, "Kokiri Forest"},
        {AreaID::KFOutsideDekuTree, "KF Outside Deku Tree"},
        {AreaID::KFLinksHouse, "KF Links House"},
        {AreaID::KFMidosHouse, "KF Midos House"},
        {AreaID::KFSariasHouse, "KF Sarias House"},
        {AreaID::KFHouseOfTwins, "KF House of Twins"},
        {AreaID::KFKnowItAllHouse, "KF Know It All House"},
        {AreaID::KFKokiriShop, "KF Kokiri Shop"},
        {AreaID::LWForestExit, "LW Forest Exit"},
        {AreaID::LostWoods, "Lost Woods"},
        {AreaID::LWBeyondMido, "LW Beyond Mido"},
        {AreaID::LostWoodsMushroomTimeout, "Lost Woods Mushroom Timeout"},
        {AreaID::SFMEntryway, "SFM Entryway"},
        {AreaID::SacredForestMeadow, "Sacred Forest Meadow"},
        {AreaID::SFMForestTempleEntranceLedge, "SFM Forest Temple Entrance Ledge"},
        {AreaID::LWBridgeFromForest, "LW Bridge From Forest"},
        {AreaID::LWBridge, "LW Bridge"},
        {AreaID::HyruleField, "Hyrule Field"},
        {AreaID::LakeHylia, "Lake Hylia"},
        {AreaID::LHFishingIsland, "LH Fishing Island"},
        {AreaID::LHOwlFlight, "LH Owl Flight"},
        {AreaID::LHLab, "LH Lab"},
        {AreaID::LHFishingHole, "LH Fishing Hole"},
        {AreaID::GerudoValley, "Gerudo Valley"},
        {AreaID::GVUpperStream, "GV Upper Stream"},
        {AreaID::GVLowerStream, "GV Lower Stream"},
        {AreaID::GVGrottoLedge, "GV Grotto Ledge"},
        {AreaID::GVCrateLedge, "GV Crate Ledge"},
        {AreaID::GVFortressSide, "GV Fortress Side"},
        {AreaID::GVCarpenterTent, "GV Carpenter Tent"},
        {AreaID::GerudoFortress, "Gerudo Fortress"},
        {AreaID::GFOutsideGate, "GF Outside Gate"},
        {AreaID::WastelandNearFortress, "Wasteland Near Fortress"},
        {AreaID::HauntedWasteland, "Haunted Wasteland"},
        {AreaID::WastelandNearColossus, "Wasteland Near Colossus"},
        {AreaID::DesertColossus, "Desert Colossus"},
        {AreaID::DesertColossusFromSpiritLobby, "Desert Colossus From Spirit Lobby"},
        {AreaID::ColossusGreatFairyFountain, "Colossus Great Fairy Fountain"},
        {AreaID::MarketEntrance, "Market Entrance"},
        {AreaID::Market, "Market"},
        {AreaID::MarketBackAlley, "Market Back Alley"},
        {AreaID::ToTEntrance, "ToT Entrance"},
        {AreaID::TempleOfTime, "Temple of Time"},
        {AreaID::BeyondDoorOfTime, "Beyond Door of Time"},
        {AreaID::CastleGrounds, "Castle Grounds"},
        {AreaID::HyruleCastleGrounds, "Hyrule Castle Grounds"},
        {AreaID::HCGarden, "HC Garden"},
        {AreaID::HCGardenLocations, "HC Garden Locations"},
        {AreaID::HCGreatFairyFountain, "HC GreatFairy Fountain"},
        {AreaID::GanonsCastleGrounds, "Ganons Castle Grounds"},
        {AreaID::OGCGreatFairyFountain, "OGC Great Fairy Fountain"},
        {AreaID::MarketGuardHouse, "Market Guard House"},
        {AreaID::MarketBazaar, "Market Bazaar"},
        {AreaID::MarketMaskShop, "Market Mask Shop"},
        {AreaID::MarketShootingGallery, "Market Shooting Gallery"},
        {AreaID::MarketBombchuBowling, "Market Bombchu Bowling"},
        {AreaID::MarketPotionShop, "Market Potion Shop"},
        {AreaID::MarketTreasureChestGame, "Market Treasure Chest Game"},
        {AreaID::MarketBombchuShop, "Market Bombchu Shop"},
        {AreaID::MarketDogLadyHouse, "Market Dog Lady House"},
        {AreaID::MarketManInGreenHouse, "Market Man in Green House"},
        {AreaID::KakarikoVillage, "Kakariko Village"},
        {AreaID::KakImpasLedge, "Kak Impas Ledge"},
        {AreaID::KakImpasRooftop, "Kak Impas Rooftop"},
        {AreaID::KakOddMedicineRooftop, "Kak Odd Medicine Rooftop"},
        {AreaID::KakBackyard, "Kak Backyard"},
        {AreaID::KakCarpenterBossHouse, "Kak Carpenter Boss House"},
        {AreaID::KakHouseOfSkulltula, "Kak House of Skulltula"},
        {AreaID::KakImpasHouse, "Kak Impas House"},
        {AreaID::KakImpasHouseBack, "Kak Impas House Back"},
        {AreaID::KakImpasHouseNearCow, "Kak Impas House Near Cow"},
        {AreaID::KakWindmill, "Kak Windmill"},
        {AreaID::KakBazaar, "Kak Bazaar"},
        {AreaID::KakShootingGallery, "Kak Shooting Gallery"},
        {AreaID::KakPotionShopFront, "Kak Potion Shop Front"},
        {AreaID::KakPotionShopBack, "Kak Potion Shop Back"},
        {AreaID::KakOddMedicineBuilding, "Kak Odd Medicine Building"},
        {AreaID::Graveyard, "Graveyard"},
        {AreaID::GraveyardShieldGrave, "Graveyard Shield Grave"},
        {AreaID::GraveyardHeartPieceGrave, "Graveyard Heart Piece Grave"},
        {AreaID::GraveyardRoyalFamilysTomb, "Graveyard Royal Familys Tomb"},
        {AreaID::GraveyardDampesGrave, "Graveyard Dampes Grave"},
        {AreaID::GraveyardDampesHouse, "Graveyard Dampes House"},
        {AreaID::GraveyardWarpPadRegion, "Graveyard Warp Pad Region"},
        {AreaID::KakBehindGate, "Kak Behind Gate"},
        {AreaID::DeathMountain, "Death Mountain"},
        {AreaID::DeathMountainSummit, "Death Mountain Summit"},
        {AreaID::DMTOwlFlight, "DMT Owl Flight"},
        {AreaID::GoronCity, "Goron City"},
        {AreaID::GCWoodsWarp, "GC Woods Warp"},
        {AreaID::GCDaruniasChamber, "GC Darunias Chamber"},
        {AreaID::GCGrottoPlatform, "GC Grotto Platform"},
        {AreaID::GCShop, "GC Shop"},
        {AreaID::DMCUpperNearby, "DMC Upper Nearby"},
        {AreaID::DMCUpperLocal, "DMC Upper Local"},
        {AreaID::DMCLadderAreaNearby, "DMC Ladder Area Nearby"},
        {AreaID::DMCLowerNearby, "DMC Lower Nearby"},
        {AreaID::DMCLowerLocal, "DMC Lower Local"},
        {AreaID::DMCCentralNearby, "DMC Central Nearby"},
        {AreaID::DMCCentralLocal, "DMC Central Local"},
        {AreaID::DMCFireTempleEntrance, "DMC FireTemple Entrance"},
        {AreaID::DMCGreatFairyFountain, "DMC Great Fairy Fountain"},
        {AreaID::DMTGreatFairyFountain, "DMT Great Fairy Fountain"},
        {AreaID::ZRFront, "ZR Front"},
        {AreaID::ZoraRiver, "Zora River"},
        {AreaID::ZRBehindWaterfall, "ZR Behind Waterfall"},
        {AreaID::ZRTopOfWaterfall, "ZR Top of Waterfall"},
        {AreaID::ZorasDomain, "Zoras Domain"},
        {AreaID::ZDBehindKingZora, "ZD Behind King Zora"},
        {AreaID::ZDEyeballFrogTimeout, "ZD Eyeball Frog Timeout"},
        {AreaID::ZorasFountain, "Zoras Fountain"},
        {AreaID::ZFIceLedge, "ZF Ice Ledge"},
        {AreaID::ZDShop, "ZD Shop"},
        {AreaID::ZFGreatFairyFountain, "ZF Great Fairy Fountain"},
        {AreaID::LonLonRanch, "Lon Lon Ranch"},
        {AreaID::LLRTalonsHouse, "LLR Talons House"},
        {AreaID::LLRStables, "LLR Stables"},
        {AreaID::LLRTower, "LLR Tower"},
        {AreaID::GanonsCastleTower, "Ganons Castle Tower"},
        {AreaID::GFStormsGrotto, "GF Storms Grotto"},
        {AreaID::ZDStormsGrotto, "ZD Storms Grotto"},
        {AreaID::KFStormsGrotto, "KF Storms Grotto"},
        {AreaID::LWNearShortcutsGrotto, "LW Near Shortcuts Grotto"},
        {AreaID::DekuTheater, "Deku Theater"},
        {AreaID::LWScrubsGrotto, "LW Scrubs Grotto"},
        {AreaID::SFMFairyGrotto, "SFM Fairy Grotto"},
        {AreaID::SFMStormsGrotto, "SFM Storms Grotto"},
        {AreaID::SFMWolfosGrotto, "SFM Wolfos Grotto"},
        {AreaID::LLRGrotto, "LLR Grotto"},
        {AreaID::HFSoutheastGrotto, "HF Southeast Grotto"},
        {AreaID::HFOpenGrotto, "HF Open Grotto"},
        {AreaID::HFInsideFenceGrotto, "HF Inside Fence Grotto"},
        {AreaID::HFCowGrotto, "HF Cow Grotto"},
        {AreaID::HFNearMarketGrotto, "HF Near Market Grotto"},
        {AreaID::HFFairyGrotto, "HF Fairy Grotto"},
        {AreaID::HFNearKakGrotto, "HF Near Kak Grotto"},
        {AreaID::HFTektiteGrotto, "HF Tektite Grotto"},
        {AreaID::HCStormsGrotto, "HC Storms Grotto"},
        {AreaID::KakRedeadGrotto, "Kak Redead Grotto"},
        {AreaID::KakOpenGrotto, "Kak Open Grotto"},
        {AreaID::DMTCowGrotto, "DMT Cow Grotto"},
        {AreaID::DMTStormsGrotto, "DMT Storms Grotto"},
        {AreaID::GCGrotto, "GC Grotto"},
        {AreaID::DMCUpperGrotto, "DMC Upper Grotto"},
        {AreaID::DMCHammerGrotto, "DMC Hammer Grotto"},
        {AreaID::ZROpenGrotto, "ZR Open Grotto"},
        {AreaID::ZRFairyGrotto, "ZR Fairy Grotto"},
        {AreaID::ZRStormsGrotto, "ZR Storms Grotto"},
        {AreaID::LHGrotto, "LH Grotto"},
        {AreaID::ColossusGrotto, "Colossus Grotto"},
        {AreaID::GVOctorokGrotto, "GV Octorok Grotto"},
        {AreaID::GVStormsGrotto, "GV Storms Grotto"},
        {AreaID::DekuTreeLobby, "Deku Tree Lobby"},
        {AreaID::DodongosCavernBeginning, "Dodongos Cavern Beginning"},
        {AreaID::JabuJabusBellyBeginning, "Jabu Jabus Belly Beginning"},
        {AreaID::ForestTempleLobby, "Forest Temple Lobby"},
        {AreaID::FireTempleLower, "Fire Temple Lower"},
        {AreaID::WaterTempleLobby, "Water Temple Lobby"},
        {AreaID::SpiritTempleLobby, "Spirit Temple Lobby"},
        {AreaID::ShadowTempleEntryway, "Shadow Temple Entryway"},
        {AreaID::IceCavernBeginning, "Ice Cavern Beginning"},
        {AreaID::BottomOfTheWell, "Bottom of the Well"},
        {AreaID::GerudoTrainingGroundLobby, "Gerudo Training Ground Lobby"},
        {AreaID::GanonsCastleLobby, "Ganons Castle Lobby"},
    };

    if (areaNameMap.count(areaId) > 0)
    {
        return areaNameMap.at(areaId);
    }
    return "INVALID";
}
