#include "item.hpp"
#include "world.hpp"

#include <unordered_map>

ItemID NameToItemID(const std::string& name)
{
  	static std::unordered_map<std::string, ItemID> nameItemMap = {
        {"None", ItemID::NONE},
        {"Kokiri_Sword", ItemID::KokiriSword},
        {"Master_Sword", ItemID::MasterSword},
        {"Giants_Knife", ItemID::GiantsKnife},
        {"Biggorons_Sword", ItemID::BiggoronsSword},
        {"Deku_Shield", ItemID::DekuShield},
        {"Hylian_Shield", ItemID::HylianShield},
        {"Mirror_Shield", ItemID::MirrorShield},
        {"Goron_Tunic", ItemID::GoronTunic},
        {"Zora_Tunic", ItemID::ZoraTunic},
        {"Iron_Boots", ItemID::IronBoots},
        {"Hover_Boots", ItemID::HoverBoots},
        {"Boomerang", ItemID::Boomerang},
        {"Lens_of_Truth", ItemID::LensOfTruth},
        {"Megaton_Hammer", ItemID::MegatonHammer},
        {"Shard_of_Agony", ItemID::ShardOfAgony},
        {"Dins_Fire", ItemID::DinsFire},
        {"Farores_Wind", ItemID::FaroresWind},
        {"Nayrus_Love", ItemID::NayrusLove},
        {"Fire_Arrows", ItemID::FireArrows},
        {"Ice_Arrows", ItemID::IceArrows},
        {"Light_Arrows", ItemID::LightArrows},
        {"Gerudo_Token", ItemID::GerudoToken},
        {"Magic_Bean", ItemID::MagicBean},
        {"Magic_Bean_Pack", ItemID::MagicBeanPack},
        {"Double_Defense", ItemID::DoubleDefense},
        {"Weird_Egg", ItemID::WeirdEgg},
        {"Cucco", ItemID::Cucco},
        {"Zeldas_Letter", ItemID::ZeldasLetter},
        {"Keaton_Mask", ItemID::KeatonMask},
        {"Skull_Mask", ItemID::SkullMask},
        {"Spooky_Mask", ItemID::SpookyMask},
        {"Bunny_Hood", ItemID::BunnyHood},
        {"Goron_Mask", ItemID::GoronMask},
        {"Zora_Mask", ItemID::ZoraMask},
        {"Gerudo_Mask", ItemID::GerudoMask},
        {"Mask_of_Truth", ItemID::MaskOfTruth},
        {"Pocket_Egg", ItemID::PocketEgg},
        {"Pocket_Cucco", ItemID::PocketCucco},
        {"Cojiro", ItemID::Cojiro},
        {"Odd_Mushroom", ItemID::OddMushroom},
        {"Odd_Poultice", ItemID::OddPoultice},
        {"Poachers_Saw", ItemID::PoachersSaw},
        {"Broken_Gorons_Sword", ItemID::BrokenGoronsSword},
        {"Prescription", ItemID::Prescription},
        {"Eyeball_Frog", ItemID::EyeballFrog},
        {"Eyedrops", ItemID::Eyedrops},
        {"Worlds_Finest_Eyedrops", ItemID::Eyedrops},
        {"Claim_Check", ItemID::ClaimCheck},
        {"Gold_Skulltula_Token", ItemID::GoldSkulltulaToken},
        {"Progressive_Hookshot", ItemID::ProgressiveHookshot},
        {"Progressive_Strength_Upgrade", ItemID::ProgressiveStrengthUpgrade},
        {"Progressive_Bomb_Bag", ItemID::ProgressiveBombBag},
        {"Bomb_Bag", ItemID::ProgressiveBombBag},
        {"Progressive_Bow", ItemID::ProgressiveBow},
        {"Bow", ItemID::ProgressiveBow},
        {"Progressive_Slingshot", ItemID::ProgressiveSlingshot},
        {"Slingshot", ItemID::ProgressiveSlingshot},
        {"Progressive_Wallet", ItemID::ProgressiveWallet},
        {"Progressive_Scale", ItemID::ProgressiveScale},
        {"Progressive_Nut_Capacity", ItemID::ProgressiveNutCapacity},
        {"Progressive_Stick_Capacity", ItemID::ProgressiveStickCapacity},
        {"Progressive_Bombchus", ItemID::ProgressiveBombchus},
        {"Bombchus", ItemID::ProgressiveBombchus},
        {"Progressive_Magic_Meter", ItemID::ProgressiveMagicMeter},
        {"Magic_Meter", ItemID::ProgressiveMagicMeter},
        {"Progressive_Ocarina", ItemID::ProgressiveOcarina},
        {"Ocarina", ItemID::ProgressiveOcarina},
        {"Progressive_Goron_Sword", ItemID::ProgressiveGoronSword},
        {"Empty_Bottle", ItemID::EmptyBottle},
        {"Bottle_with_Milk", ItemID::BottleWithMilk},
        {"Bottle_with_Red_Potion", ItemID::BottleWithRedPotion},
        {"Bottle_with_Green_Potion", ItemID::BottleWithGreenPotion},
        {"Bottle_with_Blue_Potion", ItemID::BottleWithBluePotion},
        {"Bottle_with_Fairy", ItemID::BottleWithFairy},
        {"Bottle_with_Fish", ItemID::BottleWithFish},
        {"Bottle_with_Blue_Fire", ItemID::BottleWithBlueFire},
        {"Bottle_with_Bugs", ItemID::BottleWithBugs},
        {"Bottle_with_Poe", ItemID::BottleWithPoe},
        {"Rutos_Letter", ItemID::RutosLetter},
        {"Bottle_with_Big_Poe", ItemID::BottleWithBigPoe},
        {"Zeldas_Lullaby", ItemID::ZeldasLullaby},
        {"Eponas_Song", ItemID::EponasSong},
        {"Sarias_Song", ItemID::SariasSong},
        {"Suns_Song", ItemID::SunsSong},
        {"Song_of_Time", ItemID::SongOfTime},
        {"Song_of_Storms", ItemID::SongOfStorms},
        {"Minuet_of_Forest", ItemID::MinuetOfForest},
        {"Bolero_of_Fire", ItemID::BoleroOfFire},
        {"Serenade_of_Water", ItemID::SerenadeOfWater},
        {"Requiem_of_Spirit", ItemID::RequiemOfSpirit},
        {"Nocturne_of_Shadow", ItemID::NocturneOfShadow},
        {"Prelude_of_Light", ItemID::PreludeOfLight},
        {"Deku_Tree_Map", ItemID::DekuTreeMap},
        {"Dodongos_Cavern_Map", ItemID::DodongosCavernMap},
        {"Jabu_Jabus_Belly_Map", ItemID::JabuJabusBellyMap},
        {"Forest_Temple_Map", ItemID::ForestTempleMap},
        {"Fire_Temple_Map", ItemID::FireTempleMap},
        {"Water_Temple_Map", ItemID::WaterTempleMap},
        {"Spirit_Temple_Map", ItemID::SpiritTempleMap},
        {"Shadow_Temple_Map", ItemID::ShadowTempleMap},
        {"Bottom_of_the_Well_Map", ItemID::BottomOfTheWellMap},
        {"Ice_Cavern_Map", ItemID::IceCavernMap},
        {"Deku_Tree_Compass", ItemID::DekuTreeCompass},
        {"Dodongos_Cavern_Compass", ItemID::DodongosCavernCompass},
        {"Jabu_Jabus_Belly_Compass", ItemID::JabuJabusBellyCompass},
        {"Forest_Temple_Compass", ItemID::ForestTempleCompass},
        {"Fire_Temple_Compass", ItemID::FireTempleCompass},
        {"Water_Temple_Compass", ItemID::WaterTempleCompass},
        {"Spirit_Temple_Compass", ItemID::SpiritTempleCompass},
        {"Shadow_Temple_Compass", ItemID::ShadowTempleCompass},
        {"Bottom_of_the_Well_Compass", ItemID::BottomOfTheWellCompass},
        {"Ice_Cavern_Compass", ItemID::IceCavernCompass},
        {"Forest_Temple_Boss_Key", ItemID::ForestTempleBossKey},
        {"Fire_Temple_Boss_Key", ItemID::FireTempleBossKey},
        {"Water_Temple_Boss_Key", ItemID::WaterTempleBossKey},
        {"Spirit_Temple_Boss_Key", ItemID::SpiritTempleBossKey},
        {"Shadow_Temple_Boss_Key", ItemID::ShadowTempleBossKey},
        {"Ganons_Castle_Boss_Key", ItemID::GanonsCastleBossKey},
        {"Forest_Temple_Small_Key", ItemID::ForestTempleSmallKey},
        {"Fire_Temple_Small_Key", ItemID::FireTempleSmallKey},
        {"Water_Temple_Small_Key", ItemID::WaterTempleSmallKey},
        {"Spirit_Temple_Small_Key", ItemID::SpiritTempleSmallKey},
        {"Shadow_Temple_Small_Key", ItemID::ShadowTempleSmallKey},
        {"Bottom_of_the_Well_Small_Key", ItemID::BottomOfTheWellSmallKey},
        {"Gerudo_Training_Ground_Small_Key", ItemID::GerudoTrainingGroundSmallKey},
        {"Thieves_Hideout_Small_Key", ItemID::ThievesHideoutSmallKey},
        {"Ganons_Castle_Small_Key", ItemID::GanonsCastleSmallKey},
        {"Chest_Game_Small_Key", ItemID::ChestGameSmallKey},
        {"Kokiri_Emerald", ItemID::KokiriEmerald},
        {"Goron_Ruby", ItemID::GoronRuby},
        {"Zora_Sapphire", ItemID::ZoraSapphire},
        {"Forest_Medallion", ItemID::ForestMedallion},
        {"Fire_Medallion", ItemID::FireMedallion},
        {"Water_Medallion", ItemID::WaterMedallion},
        {"Spirit_Medallion", ItemID::SpiritMedallion},
        {"Shadow_Medallion", ItemID::ShadowMedallion},
        {"Light_Medallion", ItemID::LightMedallion},
        {"Recovery_Heart", ItemID::RecoveryHeart},
        {"Green_Rupee", ItemID::GreenRupee},
        {"Blue_Rupee", ItemID::BlueRupee},
        {"Red_Rupee", ItemID::RedRupee},
        {"Purple_Rupee", ItemID::PurpleRupee},
        {"Huge_Rupee", ItemID::HugeRupee},
        {"Piece_of_Heart", ItemID::PieceOfHeart},
        {"Heart_Container", ItemID::HeartContainer},
        {"Ice_Trap", ItemID::IceTrap},
        {"Milk", ItemID::Milk},
        {"Bombs_5", ItemID::Bombs5},
        {"Bombs_10", ItemID::Bombs10},
        {"Bombs_20", ItemID::Bombs20},
        {"Bombchus_5", ItemID::Bombchus5},
        {"Bombchus_10", ItemID::Bombchus10},
        {"Bombchus_20", ItemID::Bombchus20},
        {"Bombchu_Drop", ItemID::BombchuDrop},
        {"Arrows_5", ItemID::Arrows5},
        {"Arrows_10", ItemID::Arrows10},
        {"Arrows_30", ItemID::Arrows30},
        {"Deku_Nuts_5", ItemID::DekuNuts5},
        {"Deku_Nuts_10", ItemID::DekuNuts10},
        {"Deku_Seeds_30", ItemID::DekuSeeds30},
        {"Deku_Stick_1", ItemID::DekuStick1},
        {"Red_Potion_Refill", ItemID::RedPotionRefill},
        {"Green_Potion_Refill", ItemID::GreenPotionRefill},
        {"Blue_Potion_Refill", ItemID::BluePotionRefill},
        {"Treasure_Game_Heart", ItemID::TreasureGameHeart},
        {"Treasure_Game_Green_Rupee", ItemID::TreasureGameGreenRupee},
        {"Buy_Deku_Nut_5", ItemID::BuyDekuNut5},
        {"Buy_Arrows_30", ItemID::BuyArrows30},
        {"Buy_Arrows_50", ItemID::BuyArrows50},
        {"Buy_Bombs_5_25", ItemID::BuyBombs525},
        {"Buy_Deku_Nut_10", ItemID::BuyDekuNut10},
        {"Buy_Deku_Stick_1", ItemID::BuyDekuStick1},
        {"Buy_Bombs_10", ItemID::BuyBombs10},
        {"Buy_Fish", ItemID::BuyFish},
        {"Buy_Red_Potion_30", ItemID::BuyRedPotion30},
        {"Buy_Green_Potion", ItemID::BuyGreenPotion},
        {"Buy_Blue_Potion", ItemID::BuyBluePotion},
        {"Buy_Hylian_Shield", ItemID::BuyHylianShield},
        {"Buy_Deku_Shield", ItemID::BuyDekuShield},
        {"Buy_Goron_Tunic", ItemID::BuyGoronTunic},
        {"Buy_Zora_Tunic", ItemID::BuyZoraTunic},
        {"Buy_Heart", ItemID::BuyHeart},
        {"Buy_Bombchu_10", ItemID::BuyBombchu10},
        {"Buy_Bombchu_20", ItemID::BuyBombchu20},
        {"Buy_Bombchu_5", ItemID::BuyBombchu5},
        {"Buy_Deku_Seeds_30", ItemID::BuyDekuSeeds30},
        {"Sold_Out", ItemID::SoldOut},
        {"Buy_Blue_Fire", ItemID::BuyBlueFire},
        {"Buy_Bottle_Bug", ItemID::BuyBottleBug},
        {"Buy_Poe", ItemID::BuyPoe},
        {"Buy_Fairys_Spirit", ItemID::BuyFairysSpirit},
        {"Buy_Arrows_10", ItemID::BuyArrows10},
        {"Buy_Bombs_20", ItemID::BuyBombs20},
        {"Buy_Bombs_30", ItemID::BuyBombs30},
        {"Buy_Bombs_5_35", ItemID::BuyBombs535},
        {"Buy_Red_Potion_40", ItemID::BuyRedPotion40},
        {"Buy_Red_Potion_50", ItemID::BuyRedPotion50},
        {"Epona", ItemID::Epona},
        {"Links_Cow", ItemID::LinksCow},
        {"Bonooru", ItemID::Bonooru},
        {"Triforce_Piece", ItemID::TriforcePiece},
        {"Time_Travel", ItemID::TimeTravel},
        {"Scarecrow_Song", ItemID::ScarecrowSong},
        {"Triforce", ItemID::Triforce},
        {"Water_Temple_Clear", ItemID::WaterTempleClear},
        {"Forest_Trial_Clear", ItemID::ForestTrialClear},
        {"Fire_Trial_Clear", ItemID::FireTrialClear},
        {"Water_Trial_Clear", ItemID::WaterTrialClear},
        {"Shadow_Trial_Clear", ItemID::ShadowTrialClear},
        {"Spirit_Trial_Clear", ItemID::SpiritTrialClear},
        {"Light_Trial_Clear", ItemID::LightTrialClear},
        {"Deku_Stick_Drop", ItemID::DekuStickDrop},
        {"Deku_Nut_Drop", ItemID::DekuNutDrop},
        {"Blue_Fire", ItemID::BlueFire},
        {"Fairy", ItemID::Fairy},
        {"Fish", ItemID::Fish},
        {"Bugs", ItemID::Bugs},
        {"Big_Poe", ItemID::BigPoe},
        {"Deku_Tree_Clear", ItemID::DekuTreeClear},
        {"Water_Temple_Clear", ItemID::WaterTempleClear},
        {"Drain_Well", ItemID::DrainWell},
        {"Showed_Mido_Sword_And_Shield", ItemID::ShowedMidoSwordAndShield},
        {"Dampes_Windmill_Access", ItemID::DampesWindmillAccess},
        {"Goron_City_Child_Fire", ItemID::GoronCityChildFire},
        {"GC_Woods_Warp_Open", ItemID::GCWoodsWarpOpen},
        {"Stop_GC_Rolling_Goron_as_Adult", ItemID::StopGCRollingGoronAsAdult},
        {"Deliver_Letter", ItemID::DeliverLetter},
        {"King_Zora_Thawed", ItemID::KingZoraThawed},
        {"Carpenter_Rescue", ItemID::CarpenterRescue},
        {"GF_Gate_Open", ItemID::GFGateOpen},
        {"GTG_Gate_Open", ItemID::GTGGateOpen},
        {"Sell_Big_Poe", ItemID::SellBigPoe},
        {"Kakariko_Village_Gate_Open", ItemID::KakarikoVillageGateOpen},
        {"Wake_Up_Adult_Talon", ItemID::WakeUpAdultTalon},
        {"Hint", ItemID::Hint},
        {"Hookshot", ItemID::Hookshot},
        {"Longshot", ItemID::Longshot},
        {"Silver_Gauntlets", ItemID::SilverGauntlets},
        {"Gold_Gauntlets", ItemID::GoldGauntlets},
        {"Scarecrow", ItemID::Scarecrow},
        {"Distant_Scarecrow", ItemID::DistantScarecrow},
        {"Sticks", ItemID::Sticks},
  	};

  	if (nameItemMap.count(name) == 0)
  	{
  		  return ItemID::INVALID;
  	}
  	return nameItemMap.at(name);
}

std::string ItemIDToName(const ItemID& itemId)
{
    static std::unordered_map<ItemID, std::string> itemNameMap = {
        {ItemID::NONE, "NONE"},
        {ItemID::KokiriSword, "Kokiri Sword"},
        {ItemID::MasterSword, "Master Sword"},
        {ItemID::GiantsKnife, "Giants Knife"},
        {ItemID::BiggoronsSword, "Biggorons Sword"},
        {ItemID::DekuShield, "Deku Shield"},
        {ItemID::HylianShield, "Hylian Shield"},
        {ItemID::MirrorShield, "Mirror Shield"},
        {ItemID::GoronTunic, "Goron Tunic"},
        {ItemID::ZoraTunic, "Zora Tunic"},
        {ItemID::IronBoots, "Iron Boots"},
        {ItemID::HoverBoots, "Hover Boots"},
        {ItemID::Boomerang, "Boomerang"},
        {ItemID::LensOfTruth, "Lens of Truth"},
        {ItemID::MegatonHammer, "Megaton Hammer"},
        {ItemID::ShardOfAgony, "Shard of Agony"},
        {ItemID::DinsFire, "Dins Fire"},
        {ItemID::FaroresWind, "Farores Wind"},
        {ItemID::NayrusLove, "Nayrus Love"},
        {ItemID::FireArrows, "Fire Arrows"},
        {ItemID::IceArrows, "Ice Arrows"},
        {ItemID::LightArrows, "Light Arrows"},
        {ItemID::GerudoToken, "Gerudo Token"},
        {ItemID::MagicBean, "Magic Bean"},
        {ItemID::MagicBeanPack, "Magic Bean Pack"},
        {ItemID::DoubleDefense, "Double Defense"},
        {ItemID::WeirdEgg, "Weird Egg"},
        {ItemID::Cucco, "Cucco"},
        {ItemID::ZeldasLetter, "Zeldas Letter"},
        {ItemID::KeatonMask, "Keaton Mask"},
        {ItemID::SkullMask, "Skull Mask"},
        {ItemID::SpookyMask, "Spooky Mask"},
        {ItemID::BunnyHood, "Bunny Hood"},
        {ItemID::GoronMask, "Goron Mask"},
        {ItemID::ZoraMask, "Zora Mask"},
        {ItemID::GerudoMask, "Gerudo Mask"},
        {ItemID::MaskOfTruth, "Mask of Truth"},
        {ItemID::PocketEgg, "Pocket Egg"},
        {ItemID::PocketCucco, "Pocket Cucco"},
        {ItemID::Cojiro, "Cojiro"},
        {ItemID::OddMushroom, "Odd Mushroom"},
        {ItemID::OddPoultice, "Odd Poultice"},
        {ItemID::PoachersSaw, "Poachers Saw"},
        {ItemID::BrokenGoronsSword, "Broken Gorons Sword"},
        {ItemID::Prescription, "Prescription"},
        {ItemID::EyeballFrog, "Eyeball Frog"},
        {ItemID::Eyedrops, "Eyedrops"},
        {ItemID::ClaimCheck, "Claim Check"},
        {ItemID::GoldSkulltulaToken, "Gold Skulltula Token"},
        {ItemID::ProgressiveHookshot, "Progressive Hookshot"},
        {ItemID::ProgressiveStrengthUpgrade, "Progressive Strength Upgrade"},
        {ItemID::ProgressiveBombBag, "Progressive Bomb Bag"},
        {ItemID::ProgressiveBow, "Progressive Bow"},
        {ItemID::ProgressiveSlingshot, "Progressive Slingshot"},
        {ItemID::ProgressiveWallet, "Progressive Wallet"},
        {ItemID::ProgressiveScale, "Progressive Scale"},
        {ItemID::ProgressiveNutCapacity, "Progressive Nut Capacity"},
        {ItemID::ProgressiveStickCapacity, "Progressive Stick Capacity"},
        {ItemID::ProgressiveBombchus, "Progressive Bombchus"},
        {ItemID::ProgressiveMagicMeter, "Progressive Magic Meter"},
        {ItemID::ProgressiveOcarina, "Progressive Ocarina"},
        {ItemID::ProgressiveGoronSword, "Progressive Goron Sword"},
        {ItemID::EmptyBottle, "Empty Bottle"},
        {ItemID::BottleWithMilk, "Bottle with Milk"},
        {ItemID::BottleWithRedPotion, "Bottle with Red Potion"},
        {ItemID::BottleWithGreenPotion, "Bottle with Green Potion"},
        {ItemID::BottleWithBluePotion, "Bottle with Blue Potion"},
        {ItemID::BottleWithFairy, "Bottle with Fairy"},
        {ItemID::BottleWithFish, "Bottle with Fish"},
        {ItemID::BottleWithBlueFire, "Bottle with Blue Fire"},
        {ItemID::BottleWithBugs, "Bottle with Bugs"},
        {ItemID::BottleWithPoe, "Bottle with Poe"},
        {ItemID::RutosLetter, "Rutos Letter"},
        {ItemID::BottleWithBigPoe, "Bottle with Big Poe"},
        {ItemID::ZeldasLullaby, "Zeldas Lullaby"},
        {ItemID::EponasSong, "Eponas Song"},
        {ItemID::SariasSong, "Sarias Song"},
        {ItemID::SunsSong, "Suns Song"},
        {ItemID::SongOfTime, "Song of Time"},
        {ItemID::SongOfStorms, "Song of Storms"},
        {ItemID::MinuetOfForest, "Minuet of Forest"},
        {ItemID::BoleroOfFire, "Bolero of Fire"},
        {ItemID::SerenadeOfWater, "Serenade of Water"},
        {ItemID::RequiemOfSpirit, "Requiem of Spirit"},
        {ItemID::NocturneOfShadow, "Nocturne of Shadow"},
        {ItemID::PreludeOfLight, "Prelude of Light"},
        {ItemID::DekuTreeMap, "Deku Tree Map"},
        {ItemID::DodongosCavernMap, "Dodongos Cavern Map"},
        {ItemID::JabuJabusBellyMap, "Jabu Jabus Belly Map"},
        {ItemID::ForestTempleMap, "Forest Temple Map"},
        {ItemID::FireTempleMap, "Fire Temple Map"},
        {ItemID::WaterTempleMap, "Water Temple Map"},
        {ItemID::SpiritTempleMap, "Spirit Temple Map"},
        {ItemID::ShadowTempleMap, "Shadow Temple Map"},
        {ItemID::BottomOfTheWellMap, "Bottom of TheWell Map"},
        {ItemID::IceCavernMap, "Ice Cavern Map"},
        {ItemID::DekuTreeCompass, "Deku Tree Compass"},
        {ItemID::DodongosCavernCompass, "Dodongos Cavern Compass"},
        {ItemID::JabuJabusBellyCompass, "Jabu Jabus Belly Compass"},
        {ItemID::ForestTempleCompass, "Forest Temple Compass"},
        {ItemID::FireTempleCompass, "Fire Temple Compass"},
        {ItemID::WaterTempleCompass, "Water Temple Compass"},
        {ItemID::SpiritTempleCompass, "Spirit Temple Compass"},
        {ItemID::ShadowTempleCompass, "Shadow Temple Compass"},
        {ItemID::BottomOfTheWellCompass, "Bottom of The Well Compass"},
        {ItemID::IceCavernCompass, "Ice Cavern Compass"},
        {ItemID::ForestTempleBossKey, "Forest Temple Boss Key"},
        {ItemID::FireTempleBossKey, "Fire Temple Boss Key"},
        {ItemID::WaterTempleBossKey, "Water Temple Boss Key"},
        {ItemID::SpiritTempleBossKey, "Spirit Temple Boss Key"},
        {ItemID::ShadowTempleBossKey, "Shadow Temple Boss Key"},
        {ItemID::GanonsCastleBossKey, "Ganons Castle Boss Key"},
        {ItemID::ForestTempleSmallKey, "Forest Temple Small Key"},
        {ItemID::FireTempleSmallKey, "Fire Temple Small Key"},
        {ItemID::WaterTempleSmallKey, "Water Temple Small Key"},
        {ItemID::SpiritTempleSmallKey, "Spirit Temple Small Key"},
        {ItemID::ShadowTempleSmallKey, "Shadow Temple Small Key"},
        {ItemID::BottomOfTheWellSmallKey, "Bottom of The Well Small Key"},
        {ItemID::GerudoTrainingGroundSmallKey, "Gerudo Training Ground Small Key"},
        {ItemID::ThievesHideoutSmallKey, "Thieves Hideout Small Key"},
        {ItemID::GanonsCastleSmallKey, "Ganons Castle Small Key"},
        {ItemID::ChestGameSmallKey, "Chest Game Small Key"},
        {ItemID::KokiriEmerald, "Kokiri Emerald"},
        {ItemID::GoronRuby, "Goron Ruby"},
        {ItemID::ZoraSapphire, "Zora Sapphire"},
        {ItemID::ForestMedallion, "Forest Medallion"},
        {ItemID::FireMedallion, "Fire Medallion"},
        {ItemID::WaterMedallion, "Water Medallion"},
        {ItemID::SpiritMedallion, "Spirit Medallion"},
        {ItemID::ShadowMedallion, "Shadow Medallion"},
        {ItemID::LightMedallion, "Light Medallion"},
        {ItemID::RecoveryHeart, "Recovery Heart"},
        {ItemID::GreenRupee, "Green Rupee"},
        {ItemID::BlueRupee, "Blue Rupee"},
        {ItemID::RedRupee, "Red Rupee"},
        {ItemID::PurpleRupee, "Purple Rupee"},
        {ItemID::HugeRupee, "Huge Rupee"},
        {ItemID::PieceOfHeart, "Piece of Heart"},
        {ItemID::HeartContainer, "Heart Container"},
        {ItemID::IceTrap, "Ice Trap"},
        {ItemID::Milk, "Milk"},
        {ItemID::Bombs5, "Bombs 5"},
        {ItemID::Bombs10, "Bombs 10"},
        {ItemID::Bombs20, "Bombs 20"},
        {ItemID::Bombchus5, "Bombchus 5"},
        {ItemID::Bombchus10, "Bombchus 10"},
        {ItemID::Bombchus20, "Bombchus 20"},
        {ItemID::BombchuDrop, "Bombchu Drop"},
        {ItemID::Arrows5, "Arrows 5"},
        {ItemID::Arrows10, "Arrows 10"},
        {ItemID::Arrows30, "Arrows 30"},
        {ItemID::DekuNuts5, "Deku Nuts 5"},
        {ItemID::DekuNuts10, "Deku Nuts 10"},
        {ItemID::DekuSeeds30, "Deku Seeds 30"},
        {ItemID::DekuStick1, "Deku Stick 1"},
        {ItemID::RedPotionRefill, "Red Potion Refill"},
        {ItemID::GreenPotionRefill, "Green Potion Refill"},
        {ItemID::BluePotionRefill, "Blue Potion Refill"},
        {ItemID::TreasureGameHeart, "Treasure Game Heart"},
        {ItemID::TreasureGameGreenRupee, "Treasure Game Green Rupee"},
        {ItemID::BuyDekuNut5, "Buy Deku Nut 5"},
        {ItemID::BuyArrows30, "Buy Arrows3 0"},
        {ItemID::BuyArrows50, "Buy Arrows 50"},
        {ItemID::BuyBombs525, "Buy Bombs 5 25"},
        {ItemID::BuyDekuNut10, "Buy Deku Nut 10"},
        {ItemID::BuyDekuStick1, "Buy Deku Stick 1"},
        {ItemID::BuyBombs10, "Buy Bombs 10"},
        {ItemID::BuyFish, "Buy Fish"},
        {ItemID::BuyRedPotion30, "Buy Red Potion 30"},
        {ItemID::BuyGreenPotion, "Buy Green Potion"},
        {ItemID::BuyBluePotion, "Buy Blue Potion"},
        {ItemID::BuyHylianShield, "Buy Hylian Shield"},
        {ItemID::BuyDekuShield, "Buy Deku Shield"},
        {ItemID::BuyGoronTunic, "Buy Goron Tunic"},
        {ItemID::BuyZoraTunic, "Buy Zora Tunic"},
        {ItemID::BuyHeart, "Buy Heart"},
        {ItemID::BuyBombchu10, "Buy Bombchu 10"},
        {ItemID::BuyBombchu20, "Buy Bombchu 20"},
        {ItemID::BuyBombchu5, "Buy Bombchu 5"},
        {ItemID::BuyDekuSeeds30, "Buy Deku Seeds 30"},
        {ItemID::SoldOut, "Sold Out"},
        {ItemID::BuyBlueFire, "Buy Blue Fire"},
        {ItemID::BuyBottleBug, "Buy Bottle Bug"},
        {ItemID::BuyPoe, "Buy Poe"},
        {ItemID::BuyFairysSpirit, "Buy Fairys Spirit"},
        {ItemID::BuyArrows10, "Buy Arrows 10"},
        {ItemID::BuyBombs20, "Buy Bombs 20"},
        {ItemID::BuyBombs30, "Buy Bombs 30"},
        {ItemID::BuyBombs535, "Buy Bombs 5 35"},
        {ItemID::BuyRedPotion40, "Buy Red Potion 40"},
        {ItemID::BuyRedPotion50, "Buy Red Potion 50"},
        // Events
        {ItemID::Epona, "Epona"},
        {ItemID::LinksCow, "Links Cow"},
        {ItemID::Bonooru, "Bonooru"},
        {ItemID::TriforcePiece, "Triforce Piece"},
        {ItemID::TimeTravel, "Time Travel"},
        {ItemID::ScarecrowSong, "Scarecrow Song"},
        {ItemID::Triforce, "Triforce"},
        {ItemID::ForestTrialClear, "Forest Trial Clear"},
        {ItemID::FireTrialClear, "Fire Trial Clear"},
        {ItemID::WaterTrialClear, "Water Trial Clear"},
        {ItemID::ShadowTrialClear, "Shadow Trial Clear"},
        {ItemID::SpiritTrialClear, "Spirit Trial Clear"},
        {ItemID::LightTrialClear, "Light Trial Clear"},
        {ItemID::DekuStickDrop, "Deku Stick Drop"},
        {ItemID::DekuNutDrop, "Deku Nut Drop"},
        {ItemID::BlueFire, "Blue Fire"},
        {ItemID::Fairy, "Fairy"},
        {ItemID::Fish, "Fish"},
        {ItemID::Bugs, "Bugs"},
        {ItemID::BigPoe, "Big Poe"},
        {ItemID::DekuTreeClear, "Deku Tree Clear"},
        {ItemID::WaterTempleClear, "Water Temple Clear"},
        {ItemID::ShowedMidoSwordAndShield, "Showed Mido Sword And Shield"},
        {ItemID::DrainWell, "Drain Well"},
        {ItemID::DampesWindmillAccess, "Dampes Windmill Access"},
        {ItemID::GoronCityChildFire, "Goron City Child Fire"},
        {ItemID::GCWoodsWarpOpen, "GC Woods Warp Open"},
        {ItemID::StopGCRollingGoronAsAdult, "Stop GC Rolling GoronAs Adult"},
        {ItemID::DeliverLetter, "Deliver Letter"},
        {ItemID::KingZoraThawed, "King Zora Thawed"},
        {ItemID::CarpenterRescue, "Carpenter Rescue"},
        {ItemID::GFGateOpen, "GF Gate Open"},
        {ItemID::GTGGateOpen, "GTG Gate Open"},
        {ItemID::SellBigPoe, "Sell Big Poe"},
        {ItemID::KakarikoVillageGateOpen, "Kakariko Village Gate Open"},
        {ItemID::WakeUpAdultTalon, "Wake Up Adult Talon"},
        {ItemID::Hint, "Hint"},
        {ItemID::Hookshot, "Hookshot"},
        {ItemID::Longshot, "Longshot"},
        {ItemID::SilverGauntlets, "Silver Gauntlets"},
        {ItemID::GoldGauntlets, "Gold Gauntlets"},
        {ItemID::Scarecrow, "Scarecrow"},
        {ItemID::DistantScarecrow, "Distant Scarecrow"},
        {ItemID::Sticks, "Sticks"}
    };

    if (itemNameMap.count(itemId) == 0)
    {
        return "INVALID";
    }
    return itemNameMap.at(itemId);
}

Item::Item() {}

Item::Item(const ItemID& id_, World* world_) : id(id_), world(world_) {
    worldId = world->GetWorldID();
    name = ItemIDToName(id_) + "[W" + std::to_string(worldId) + "]";
}

Item::~Item() = default;

ItemID Item::GetID() const
{
    return id;
}

std::string Item::GetName() const
{
    return name;
}

World* Item::GetWorld() const
{
    return world;
}

int Item::GetWorldID() const
{
    return worldId;
}

bool Item::operator==(const Item& rhs) const
{
		return id == rhs.id && worldId == rhs.worldId;
}

bool Item::operator<(const Item& rhs) const
{
		return (worldId == rhs.worldId) ? id < rhs.id : worldId < rhs.worldId;
}
