#include "location.hpp"
#include <unordered_map>

LocationID NameToLocationID(const std::string& name)
{
    static std::unordered_map<std::string, LocationID> nameLocationMap = {
        {"NONE", LocationID::NONE},
        {"Links Pocket", LocationID::LinksPocket},
        {"Queen Gohma", LocationID::QueenGohma},
        {"King Dodongo", LocationID::KingDodongo},
        {"Barinade", LocationID::Barinade},
        {"Phantom Ganon", LocationID::PhantomGanon},
        {"Volvagia", LocationID::Volvagia},
        {"Morpha", LocationID::Morpha},
        {"Bongo Bongo", LocationID::BongoBongo},
        {"Twinrova", LocationID::Twinrova},
        {"Ganon", LocationID::Ganon},
        {"Gift from Sages", LocationID::GiftfromSages},
        {"Song from Impa", LocationID::SongfromImpa},
        {"Song from Malon", LocationID::SongfromMalon},
        {"Song from Saria", LocationID::SongfromSaria},
        {"Song from Royal Familys Tomb", LocationID::SongfromRoyalFamilysTomb},
        {"Song from Ocarina of Time", LocationID::SongfromOcarinaofTime},
        {"Song from Windmill", LocationID::SongfromWindmill},
        {"Sheik in Forest", LocationID::SheikInForest},
        {"Sheik in Crater", LocationID::SheikInCrater},
        {"Sheik in Ice Cavern", LocationID::SheikInIceCavern},
        {"Sheik at Colossus", LocationID::SheikAtColossus},
        {"Sheik in Kakariko", LocationID::SheikInKakariko},
        {"Sheik at Temple", LocationID::SheikAtTemple},
        {"KF Midos Top Left Chest", LocationID::KFMidosTopLeftChest},
        {"KF Midos Top Right Chest", LocationID::KFMidosTopRightChest},
        {"KF Midos Bottom Left Chest", LocationID::KFMidosBottomLeftChest},
        {"KF Midos Bottom Right Chest", LocationID::KFMidosBottomRightChest},
        {"KF Kokiri Sword Chest", LocationID::KFKokiriSwordChest},
        {"KF Storms Grotto Chest", LocationID::KFStormsGrottoChest},
        {"KF Links House Cow", LocationID::KFLinksHouseCow},
        {"KF GS Know It All House", LocationID::KFGSKnowItAllHouse},
        {"KF GS Bean Patch", LocationID::KFGSBeanPatch},
        {"KF GS House of Twins", LocationID::KFGSHouseofTwins},
        {"KF Shop Item 1", LocationID::KFShopItem1},
        {"KF Shop Item 2", LocationID::KFShopItem2},
        {"KF Shop Item 3", LocationID::KFShopItem3},
        {"KF Shop Item 4", LocationID::KFShopItem4},
        {"KF Shop Item 5", LocationID::KFShopItem5},
        {"KF Shop Item 6", LocationID::KFShopItem6},
        {"KF Shop Item 7", LocationID::KFShopItem7},
        {"KF Shop Item 8", LocationID::KFShopItem8},
        {"LW Gift from Saria", LocationID::LWGiftfromSaria},
        {"LW Ocarina Memory Game", LocationID::LWOcarinaMemoryGame},
        {"LW Target in Woods", LocationID::LWTargetInWoods},
        {"LW Near Shortcuts Grotto Chest", LocationID::LWNearShortcutsGrottoChest},
        {"Deku Theater Skull Mask", LocationID::DekuTheaterSkullMask},
        {"Deku Theater Mask of Truth", LocationID::DekuTheaterMaskofTruth},
        {"LW Skull Kid", LocationID::LWSkullKid},
        {"LW Trade Cojiro", LocationID::LWTradeCojiro},
        {"LW Trade Odd Poultice", LocationID::LWTradeOddPoultice},
        {"LW Deku Scrub Near Bridge", LocationID::LWDekuScrubNearBridge},
        {"LW Deku Scrub Near Deku Theater Left", LocationID::LWDekuScrubNearDekuTheaterLeft},
        {"LW Deku Scrub Near Deku Theater Right", LocationID::LWDekuScrubNearDekuTheaterRight},
        {"LW Deku Scrub Grotto Front", LocationID::LWDekuScrubGrottoFront},
        {"LW Deku Scrub Grotto Rear", LocationID::LWDekuScrubGrottoRear},
        {"LW GS Bean Patch Near Bridge", LocationID::LWGSBeanPatchNearBridge},
        {"LW GS Bean Patch Near Theater", LocationID::LWGSBeanPatchNearTheater},
        {"LW GS Above Theater", LocationID::LWGSAboveTheater},
        {"SFM Wolfos Grotto Chest", LocationID::SFMWolfosGrottoChest},
        {"SFM Deku Scrub Grotto Front", LocationID::SFMDekuScrubGrottoFront},
        {"SFM Deku Scrub Grotto Rear", LocationID::SFMDekuScrubGrottoRear},
        {"SFM GS", LocationID::SFMGS},
        {"HF Ocarina of Time Item", LocationID::HFOcarinaofTimeItem},
        {"HF Near Market Grotto Chest", LocationID::HFNearMarketGrottoChest},
        {"HF Tektite Grotto Freestanding PoH", LocationID::HFTektiteGrottoFreestandingPoH},
        {"HF Southeast Grotto Chest", LocationID::HFSoutheastGrottoChest},
        {"HF Open Grotto Chest", LocationID::HFOpenGrottoChest},
        {"HF Deku Scrub Grotto", LocationID::HFDekuScrubGrotto},
        {"HF Cow Grotto Cow", LocationID::HFCowGrottoCow},
        {"HF GS Cow Grotto", LocationID::HFGSCowGrotto},
        {"HF GS Near Kak Grotto", LocationID::HFGSNearKakGrotto},
        {"Market Shooting Gallery Reward", LocationID::MarketShootingGalleryReward},
        {"Market Bombchu Bowling First Prize", LocationID::MarketBombchuBowlingFirstPrize},
        {"Market Bombchu Bowling Second Prize", LocationID::MarketBombchuBowlingSecondPrize},
        {"Market Bombchu Bowling Bombchus", LocationID::MarketBombchuBowlingBombchus},
        {"Market Lost Dog", LocationID::MarketLostDog},
        {"Market Chest Game First Room Chest", LocationID::MarketChestGameFirstRoomChest},
        {"Market Chest Game Second Room Chest", LocationID::MarketChestGameSecondRoomChest},
        {"Market Chest Game Third Room Chest", LocationID::MarketChestGameThirdRoomChest},
        {"Market Chest Game Fourth Room Chest", LocationID::MarketChestGameFourthRoomChest},
        {"Market Chest Game Fifth Room Chest", LocationID::MarketChestGameFifthRoomChest},
        {"Market Treasure Chest Game Reward", LocationID::MarketTreasureChestGameReward},
        {"Market 10 Big Poes", LocationID::Market10BigPoes},
        {"Market GS Guard House", LocationID::MarketGSGuardHouse},
        {"Market Bazaar Item 1", LocationID::MarketBazaarItem1},
        {"Market Bazaar Item 2", LocationID::MarketBazaarItem2},
        {"Market Bazaar Item 3", LocationID::MarketBazaarItem3},
        {"Market Bazaar Item 4", LocationID::MarketBazaarItem4},
        {"Market Bazaar Item 5", LocationID::MarketBazaarItem5},
        {"Market Bazaar Item 6", LocationID::MarketBazaarItem6},
        {"Market Bazaar Item 7", LocationID::MarketBazaarItem7},
        {"Market Bazaar Item 8", LocationID::MarketBazaarItem8},
        {"Market Potion Shop Item 1", LocationID::MarketPotionShopItem1},
        {"Market Potion Shop Item 2", LocationID::MarketPotionShopItem2},
        {"Market Potion Shop Item 3", LocationID::MarketPotionShopItem3},
        {"Market Potion Shop Item 4", LocationID::MarketPotionShopItem4},
        {"Market Potion Shop Item 5", LocationID::MarketPotionShopItem5},
        {"Market Potion Shop Item 6", LocationID::MarketPotionShopItem6},
        {"Market Potion Shop Item 7", LocationID::MarketPotionShopItem7},
        {"Market Potion Shop Item 8", LocationID::MarketPotionShopItem8},
        {"Market Bombchu Shop Item 1", LocationID::MarketBombchuShopItem1},
        {"Market Bombchu Shop Item 2", LocationID::MarketBombchuShopItem2},
        {"Market Bombchu Shop Item 3", LocationID::MarketBombchuShopItem3},
        {"Market Bombchu Shop Item 4", LocationID::MarketBombchuShopItem4},
        {"Market Bombchu Shop Item 5", LocationID::MarketBombchuShopItem5},
        {"Market Bombchu Shop Item 6", LocationID::MarketBombchuShopItem6},
        {"Market Bombchu Shop Item 7", LocationID::MarketBombchuShopItem7},
        {"Market Bombchu Shop Item 8", LocationID::MarketBombchuShopItem8},
        {"ToT Light Arrows Cutscene", LocationID::ToTLightArrowsCutscene},
        {"HC Malon Egg", LocationID::HCMalonEgg},
        {"HC Zeldas Letter", LocationID::HCZeldasLetter},
        {"HC Great Fairy Reward", LocationID::HCGreatFairyReward},
        {"HC GS Tree", LocationID::HCGSTree},
        {"HC GS Storms Grotto", LocationID::HCGSStormsGrotto},
        {"LLR Talons Chickens", LocationID::LLRTalonsChickens},
        {"LLR Freestanding PoH", LocationID::LLRFreestandingPoH},
        {"LLR Deku Scrub Grotto Left", LocationID::LLRDekuScrubGrottoLeft},
        {"LLR Deku Scrub Grotto Center", LocationID::LLRDekuScrubGrottoCenter},
        {"LLR Deku Scrub Grotto Right", LocationID::LLRDekuScrubGrottoRight},
        {"LLR Stables Left Cow", LocationID::LLRStablesLeftCow},
        {"LLR Stables Right Cow", LocationID::LLRStablesRightCow},
        {"LLR Tower Left Cow", LocationID::LLRTowerLeftCow},
        {"LLR Tower Right Cow", LocationID::LLRTowerRightCow},
        {"LLR GS House Window", LocationID::LLRGSHouseWindow},
        {"LLR GS Tree", LocationID::LLRGSTree},
        {"LLR GS Rain Shed", LocationID::LLRGSRainShed},
        {"LLR GS Back Wall", LocationID::LLRGSBackWall},
        {"Kak Anju as Child", LocationID::KakAnjuasChild},
        {"Kak Anju as Adult", LocationID::KakAnjuasAdult},
        {"Kak Trade Pocket Cucco", LocationID::KakTradePocketCucco},
        {"Kak Impas House Freestanding PoH", LocationID::KakImpasHouseFreestandingPoH},
        {"Kak Windmill Freestanding PoH", LocationID::KakWindmillFreestandingPoH},
        {"Kak Man on Roof", LocationID::KakManonRoof},
        {"Kak Open Grotto Chest", LocationID::KakOpenGrottoChest},
        {"Kak Redead Grotto Chest", LocationID::KakRedeadGrottoChest},
        {"Kak Trade Odd Mushroom", LocationID::KakTradeOddMushroom},
        {"Kak Shooting Gallery Reward", LocationID::KakShootingGalleryReward},
        {"Kak 10 Gold Skulltula Reward", LocationID::Kak10GoldSkulltulaReward},
        {"Kak 20 Gold Skulltula Reward", LocationID::Kak20GoldSkulltulaReward},
        {"Kak 30 Gold Skulltula Reward", LocationID::Kak30GoldSkulltulaReward},
        {"Kak 40 Gold Skulltula Reward", LocationID::Kak40GoldSkulltulaReward},
        {"Kak 50 Gold Skulltula Reward", LocationID::Kak50GoldSkulltulaReward},
        {"Kak Impas House Cow", LocationID::KakImpasHouseCow},
        {"Kak GS Tree", LocationID::KakGSTree},
        {"Kak GS Guards House", LocationID::KakGSGuardsHouse},
        {"Kak GS Watchtower", LocationID::KakGSWatchtower},
        {"Kak GS Skulltula House", LocationID::KakGSSkulltulaHouse},
        {"Kak GS House Under Construction", LocationID::KakGSHouseUnderConstruction},
        {"Kak GS Above Impas House", LocationID::KakGSAboveImpasHouse},
        {"Kak Bazaar Item 1", LocationID::KakBazaarItem1},
        {"Kak Bazaar Item 2", LocationID::KakBazaarItem2},
        {"Kak Bazaar Item 3", LocationID::KakBazaarItem3},
        {"Kak Bazaar Item 4", LocationID::KakBazaarItem4},
        {"Kak Bazaar Item 5", LocationID::KakBazaarItem5},
        {"Kak Bazaar Item 6", LocationID::KakBazaarItem6},
        {"Kak Bazaar Item 7", LocationID::KakBazaarItem7},
        {"Kak Bazaar Item 8", LocationID::KakBazaarItem8},
        {"Kak Potion Shop Item 1", LocationID::KakPotionShopItem1},
        {"Kak Potion Shop Item 2", LocationID::KakPotionShopItem2},
        {"Kak Potion Shop Item 3", LocationID::KakPotionShopItem3},
        {"Kak Potion Shop Item 4", LocationID::KakPotionShopItem4},
        {"Kak Potion Shop Item 5", LocationID::KakPotionShopItem5},
        {"Kak Potion Shop Item 6", LocationID::KakPotionShopItem6},
        {"Kak Potion Shop Item 7", LocationID::KakPotionShopItem7},
        {"Kak Potion Shop Item 8", LocationID::KakPotionShopItem8},
        {"Graveyard Shield Grave Chest", LocationID::GraveyardShieldGraveChest},
        {"Graveyard Heart Piece Grave Chest", LocationID::GraveyardHeartPieceGraveChest},
        {"Graveyard Royal Familys Tomb Chest", LocationID::GraveyardRoyalFamilysTombChest},
        {"Graveyard Freestanding PoH", LocationID::GraveyardFreestandingPoH},
        {"Graveyard Dampe Gravedigging Tour", LocationID::GraveyardDampeGravediggingTour},
        {"Graveyard Hookshot Chest", LocationID::GraveyardHookshotChest},
        {"Graveyard Dampe Race Freestanding PoH", LocationID::GraveyardDampeRaceFreestandingPoH},
        {"Graveyard GS Bean Patch", LocationID::GraveyardGSBeanPatch},
        {"Graveyard GS Wall", LocationID::GraveyardGSWall},
        {"DMT Freestanding PoH", LocationID::DMTFreestandingPoH},
        {"DMT Chest", LocationID::DMTChest},
        {"DMT Storms Grotto Chest", LocationID::DMTStormsGrottoChest},
        {"DMT Great Fairy Reward", LocationID::DMTGreatFairyReward},
        {"DMT Trade Broken Sword", LocationID::DMTTradeBrokenSword},
        {"DMT Trade Eyedrops", LocationID::DMTTradeEyedrops},
        {"DMT Trade Claim Check", LocationID::DMTTradeClaimCheck},
        {"DMT Cow Grotto Cow", LocationID::DMTCowGrottoCow},
        {"DMT GS Near Kak", LocationID::DMTGSNearKak},
        {"DMT GS Bean Patch", LocationID::DMTGSBeanPatch},
        {"DMT GS Above Dodongos Cavern", LocationID::DMTGSAboveDodongosCavern},
        {"DMT GS Falling Rocks Path", LocationID::DMTGSFallingRocksPath},
        {"GC Darunias Joy", LocationID::GCDaruniasJoy},
        {"GC Pot Freestanding PoH", LocationID::GCPotFreestandingPoH},
        {"GC Rolling Goron as Child", LocationID::GCRollingGoronasChild},
        {"GC Rolling Goron as Adult", LocationID::GCRollingGoronasAdult},
        {"GC Medigoron", LocationID::GCMedigoron},
        {"GC Maze Left Chest", LocationID::GCMazeLeftChest},
        {"GC Maze Right Chest", LocationID::GCMazeRightChest},
        {"GC Maze Center Chest", LocationID::GCMazeCenterChest},
        {"GC Deku Scrub Grotto Left", LocationID::GCDekuScrubGrottoLeft},
        {"GC Deku Scrub Grotto Center", LocationID::GCDekuScrubGrottoCenter},
        {"GC Deku Scrub Grotto Right", LocationID::GCDekuScrubGrottoRight},
        {"GC GS Center Platform", LocationID::GCGSCenterPlatform},
        {"GC GS Boulder Maze", LocationID::GCGSBoulderMaze},
        {"GC Shop Item 1", LocationID::GCShopItem1},
        {"GC Shop Item 2", LocationID::GCShopItem2},
        {"GC Shop Item 3", LocationID::GCShopItem3},
        {"GC Shop Item 4", LocationID::GCShopItem4},
        {"GC Shop Item 5", LocationID::GCShopItem5},
        {"GC Shop Item 6", LocationID::GCShopItem6},
        {"GC Shop Item 7", LocationID::GCShopItem7},
        {"GC Shop Item 8", LocationID::GCShopItem8},
        {"DMC Volcano Freestanding PoH", LocationID::DMCVolcanoFreestandingPoH},
        {"DMC Wall Freestanding PoH", LocationID::DMCWallFreestandingPoH},
        {"DMC Upper Grotto Chest", LocationID::DMCUpperGrottoChest},
        {"DMC Great Fairy Reward", LocationID::DMCGreatFairyReward},
        {"DMC Deku Scrub", LocationID::DMCDekuScrub},
        {"DMC Deku Scrub Grotto Left", LocationID::DMCDekuScrubGrottoLeft},
        {"DMC Deku Scrub Grotto Center", LocationID::DMCDekuScrubGrottoCenter},
        {"DMC Deku Scrub Grotto Right", LocationID::DMCDekuScrubGrottoRight},
        {"DMC GS Crate", LocationID::DMCGSCrate},
        {"DMC GS Bean Patch", LocationID::DMCGSBeanPatch},
        {"ZR Magic Bean Salesman", LocationID::ZRMagicBeanSalesman},
        {"ZR Open Grotto Chest", LocationID::ZROpenGrottoChest},
        {"ZR Frogs in the Rain", LocationID::ZRFrogsintheRain},
        {"ZR Frogs Ocarina Game", LocationID::ZRFrogsOcarinaGame},
        {"ZR Near Open Grotto Freestanding PoH", LocationID::ZRNearOpenGrottoFreestandingPoH},
        {"ZR Near Domain Freestanding PoH" , LocationID::ZRNearDomainFreestandingPoH},
        {"ZR Deku Scrub Grotto Front", LocationID::ZRDekuScrubGrottoFront},
        {"ZR Deku Scrub Grotto Rear", LocationID::ZRDekuScrubGrottoRear},
        {"ZR GS Tree", LocationID::ZRGSTree},
        {"ZR GS Ladder", LocationID::ZRGSLadder},
        {"ZR GS Near Raised Grottos", LocationID::ZRGSNearRaisedGrottos},
        {"ZR GS Above Bridge", LocationID::ZRGSAboveBridge},
        {"ZD Diving Minigame", LocationID::ZDDivingMinigame},
        {"ZD Chest", LocationID::ZDChest},
        {"ZD King Zora Thawed", LocationID::ZDKingZoraThawed},
        {"ZD Trade Prescription", LocationID::ZDTradePrescription},
        {"ZD GS Frozen Waterfall", LocationID::ZDGSFrozenWaterfall},
        {"ZD Shop Item 1", LocationID::ZDShopItem1},
        {"ZD Shop Item 2", LocationID::ZDShopItem2},
        {"ZD Shop Item 3", LocationID::ZDShopItem3},
        {"ZD Shop Item 4", LocationID::ZDShopItem4},
        {"ZD Shop Item 5", LocationID::ZDShopItem5},
        {"ZD Shop Item 6", LocationID::ZDShopItem6},
        {"ZD Shop Item 7", LocationID::ZDShopItem7},
        {"ZD Shop Item 8", LocationID::ZDShopItem8},
        {"ZF Great Fairy Reward", LocationID::ZFGreatFairyReward},
        {"ZF Iceberg Freestanding PoH", LocationID::ZFIcebergFreestandingPoH},
        {"ZF Bottom Freestanding PoH", LocationID::ZFBottomFreestandingPoH},
        {"ZF GS Above the Log", LocationID::ZFGSAbovetheLog},
        {"ZF GS Tree", LocationID::ZFGSTree},
        {"ZF GS Hidden Cave", LocationID::ZFGSHiddenCave},
        {"LH Underwater Item", LocationID::LHUnderwaterItem},
        {"LH Child Fishing", LocationID::LHChildFishing},
        {"LH Adult Fishing", LocationID::LHAdultFishing},
        {"LH Lab Dive", LocationID::LHLabDive},
        {"LH Lab Trade Eyeball Frog", LocationID::LHLabTradeEyeballFrog},
        {"LH Freestanding PoH", LocationID::LHFreestandingPoH},
        {"LH Sun", LocationID::LHSun},
        {"LH Deku Scrub Grotto Left", LocationID::LHDekuScrubGrottoLeft},
        {"LH Deku Scrub Grotto Center", LocationID::LHDekuScrubGrottoCenter},
        {"LH Deku Scrub Grotto Right", LocationID::LHDekuScrubGrottoRight},
        {"LH GS Bean Patch", LocationID::LHGSBeanPatch},
        {"LH GS Lab Wall", LocationID::LHGSLabWall},
        {"LH GS Small Island", LocationID::LHGSSmallIsland},
        {"LH GS Lab Crate", LocationID::LHGSLabCrate},
        {"LH GS Tree", LocationID::LHGSTree},
        {"GV Crate Freestanding PoH", LocationID::GVCrateFreestandingPoH},
        {"GV Waterfall Freestanding PoH" , LocationID::GVWaterfallFreestandingPoH},
        {"GV Chest", LocationID::GVChest},
        {"GV Trade Saw", LocationID::GVTradeSaw},
        {"GV Deku Scrub Grotto Front", LocationID::GVDekuScrubGrottoFront},
        {"GV Deku Scrub Grotto Rear", LocationID::GVDekuScrubGrottoRear},
        {"GV Cow", LocationID::GVCow},
        {"GV GS Small Bridge", LocationID::GVGSSmallBridge},
        {"GV GS Bean Patch", LocationID::GVGSBeanPatch},
        {"GV GS Behind Tent", LocationID::GVGSBehindTent},
        {"GV GS Pillar", LocationID::GVGSPillar},
        {"GF Chest", LocationID::GFChest},
        {"GF HBA 1000 Points", LocationID::GFHBA1000Points},
        {"GF HBA 1500 Points", LocationID::GFHBA1500Points},
        {"GF GS Top Floor", LocationID::GFGSTopFloor},
        {"GF GS Archery Range", LocationID::GFGSArcheryRange},
        {"Hideout Jail Guard 1 Torch", LocationID::HideoutJailGuard1Torch},
        {"Hideout Jail Guard 2 Torches", LocationID::HideoutJailGuard2Torches},
        {"Hideout Jail Guard 3 Torches", LocationID::HideoutJailGuard3Torches},
        {"Hideout Jail Guard 4 Torches", LocationID::HideoutJailGuard4Torches},
        {"Hideout Gerudo Token", LocationID::HideoutGerudoToken},
        {"Wasteland Bombchu Salesman", LocationID::WastelandBombchuSalesman},
        {"Wasteland Chest", LocationID::WastelandChest},
        {"Wasteland GS", LocationID::WastelandGS},
        {"Colossus Great Fairy Reward", LocationID::ColossusGreatFairyReward},
        {"Colossus Freestanding PoH" , LocationID::ColossusFreestandingPoH},
        {"Colossus Deku Scrub Grotto Front", LocationID::ColossusDekuScrubGrottoFront},
        {"Colossus Deku Scrub Grotto Rear", LocationID::ColossusDekuScrubGrottoRear},
        {"Colossus GS Bean Patch", LocationID::ColossusGSBeanPatch},
        {"Colossus GS Tree", LocationID::ColossusGSTree},
        {"Colossus GS Hill", LocationID::ColossusGSHill},
        {"OGC Great Fairy Reward", LocationID::OGCGreatFairyReward},
        {"OGC GS", LocationID::OGCGS},
        {"Deku Tree Map Chest", LocationID::DekuTreeMapChest},
        {"Deku Tree Slingshot Room Side Chest", LocationID::DekuTreeSlingshotRoomSideChest},
        {"Deku Tree Slingshot Chest", LocationID::DekuTreeSlingshotChest},
        {"Deku Tree Compass Chest", LocationID::DekuTreeCompassChest},
        {"Deku Tree Compass Room Side Chest", LocationID::DekuTreeCompassRoomSideChest},
        {"Deku Tree Basement Chest", LocationID::DekuTreeBasementChest},
        {"Deku Tree GS Compass Room", LocationID::DekuTreeGSCompassRoom},
        {"Deku Tree GS Basement Vines", LocationID::DekuTreeGSBasementVines},
        {"Deku Tree GS Basement Gate", LocationID::DekuTreeGSBasementGate},
        {"Deku Tree GS Basement Back Room", LocationID::DekuTreeGSBasementBackRoom},
        {"Deku Tree MQ Map Chest", LocationID::DekuTreeMQMapChest},
        {"Deku Tree MQ Slingshot Chest", LocationID::DekuTreeMQSlingshotChest},
        {"Deku Tree MQ Slingshot Room Back Chest", LocationID::DekuTreeMQSlingshotRoomBackChest},
        {"Deku Tree MQ Compass Chest", LocationID::DekuTreeMQCompassChest},
        {"Deku Tree MQ Basement Chest", LocationID::DekuTreeMQBasementChest},
        {"Deku Tree MQ Before Spinning Log Chest", LocationID::DekuTreeMQBeforeSpinningLogChest},
        {"Deku Tree MQ After Spinning Log Chest", LocationID::DekuTreeMQAfterSpinningLogChest},
        {"Deku Tree MQ Deku Scrub", LocationID::DekuTreeMQDekuScrub},
        {"Deku Tree MQ GS Lobby", LocationID::DekuTreeMQGSLobby},
        {"Deku Tree MQ GS Compass Room", LocationID::DekuTreeMQGSCompassRoom},
        {"Deku Tree MQ GS Basement Graves Room", LocationID::DekuTreeMQGSBasementGravesRoom},
        {"Deku Tree MQ GS Basement Back Room", LocationID::DekuTreeMQGSBasementBackRoom},
        {"Deku Tree Queen Gohma Heart", LocationID::DekuTreeQueenGohmaHeart},
        {"Dodongos Cavern Map Chest", LocationID::DodongosCavernMapChest},
        {"Dodongos Cavern Compass Chest", LocationID::DodongosCavernCompassChest},
        {"Dodongos Cavern Bomb Flower Platform Chest", LocationID::DodongosCavernBombFlowerPlatformChest},
        {"Dodongos Cavern Bomb Bag Chest", LocationID::DodongosCavernBombBagChest},
        {"Dodongos Cavern End of Bridge Chest", LocationID::DodongosCavernEndofBridgeChest},
        {"Dodongos Cavern Deku Scrub Side Room Near Dodongos", LocationID::DodongosCavernDekuScrubSideRoomNearDodongos},
        {"Dodongos Cavern Deku Scrub Lobby", LocationID::DodongosCavernDekuScrubLobby},
        {"Dodongos Cavern Deku Scrub Near Bomb Bag Left", LocationID::DodongosCavernDekuScrubNearBombBagLeft},
        {"Dodongos Cavern Deku Scrub Near Bomb Bag Right", LocationID::DodongosCavernDekuScrubNearBombBagRight},
        {"Dodongos Cavern GS Side Room Near Lower Lizalfos", LocationID::DodongosCavernGSSideRoomNearLowerLizalfos},
        {"Dodongos Cavern GS Scarecrow", LocationID::DodongosCavernGSScarecrow},
        {"Dodongos Cavern GS Alcove Above Stairs", LocationID::DodongosCavernGSAlcoveAboveStairs},
        {"Dodongos Cavern GS Vines Above Stairs", LocationID::DodongosCavernGSVinesAboveStairs},
        {"Dodongos Cavern GS Back Room", LocationID::DodongosCavernGSBackRoom},
        {"Dodongos Cavern MQ Map Chest", LocationID::DodongosCavernMQMapChest},
        {"Dodongos Cavern MQ Bomb Bag Chest", LocationID::DodongosCavernMQBombBagChest},
        {"Dodongos Cavern MQ Torch Puzzle Room Chest", LocationID::DodongosCavernMQTorchPuzzleRoomChest},
        {"Dodongos Cavern MQ Larvae Room Chest", LocationID::DodongosCavernMQLarvaeRoomChest},
        {"Dodongos Cavern MQ Compass Chest", LocationID::DodongosCavernMQCompassChest},
        {"Dodongos Cavern MQ Under Grave Chest", LocationID::DodongosCavernMQUnderGraveChest},
        {"Dodongos Cavern MQ Deku Scrub Lobby Front", LocationID::DodongosCavernMQDekuScrubLobbyFront},
        {"Dodongos Cavern MQ Deku Scrub Lobby Rear", LocationID::DodongosCavernMQDekuScrubLobbyRear},
        {"Dodongos Cavern MQ Deku Scrub Side Room Near Lower Lizalfos", LocationID::DodongosCavernMQDekuScrubSideRoomNearLowerLizalfos},
        {"Dodongos Cavern MQ Deku Scrub Staircase", LocationID::DodongosCavernMQDekuScrubStaircase},
        {"Dodongos Cavern MQ GS Scrub Room", LocationID::DodongosCavernMQGSScrubRoom},
        {"Dodongos Cavern MQ GS Larvae Room", LocationID::DodongosCavernMQGSLarvaeRoom},
        {"Dodongos Cavern MQ GS Lizalfos Room", LocationID::DodongosCavernMQGSLizalfosRoom},
        {"Dodongos Cavern MQ GS Song of Time Block Room", LocationID::DodongosCavernMQGSSongofTimeBlockRoom},
        {"Dodongos Cavern MQ GS Back Area", LocationID::DodongosCavernMQGSBackArea},
        {"Dodongos Cavern Boss Room Chest", LocationID::DodongosCavernBossRoomChest},
        {"Dodongos Cavern King Dodongo Heart", LocationID::DodongosCavernKingDodongoHeart},
        {"Jabu Jabus Belly Boomerang Chest", LocationID::JabuJabusBellyBoomerangChest},
        {"Jabu Jabus Belly Map Chest", LocationID::JabuJabusBellyMapChest},
        {"Jabu Jabus Belly Compass Chest", LocationID::JabuJabusBellyCompassChest},
        {"Jabu Jabus Belly Deku Scrub", LocationID::JabuJabusBellyDekuScrub},
        {"Jabu Jabus Belly GS Water Switch Room", LocationID::JabuJabusBellyGSWaterSwitchRoom},
        {"Jabu Jabus Belly GS Lobby Basement Lower", LocationID::JabuJabusBellyGSLobbyBasementLower},
        {"Jabu Jabus Belly GS Lobby Basement Upper", LocationID::JabuJabusBellyGSLobbyBasementUpper},
        {"Jabu Jabus Belly GS Near Boss", LocationID::JabuJabusBellyGSNearBoss},
        {"Jabu Jabus Belly MQ Map Chest", LocationID::JabuJabusBellyMQMapChest},
        {"Jabu Jabus Belly MQ First Room Side Chest", LocationID::JabuJabusBellyMQFirstRoomSideChest},
        {"Jabu Jabus Belly MQ Second Room Lower Chest", LocationID::JabuJabusBellyMQSecondRoomLowerChest},
        {"Jabu Jabus Belly MQ Compass Chest", LocationID::JabuJabusBellyMQCompassChest},
        {"Jabu Jabus Belly MQ Basement Near Switches Chest", LocationID::JabuJabusBellyMQBasementNearSwitchesChest},
        {"Jabu Jabus Belly MQ Basement Near Vines Chest", LocationID::JabuJabusBellyMQBasementNearVinesChest},
        {"Jabu Jabus Belly MQ Boomerang Room Small Chest", LocationID::JabuJabusBellyMQBoomerangRoomSmallChest},
        {"Jabu Jabus Belly MQ Boomerang Chest", LocationID::JabuJabusBellyMQBoomerangChest},
        {"Jabu Jabus Belly MQ Falling Like Like Room Chest", LocationID::JabuJabusBellyMQFallingLikeLikeRoomChest},
        {"Jabu Jabus Belly MQ Second Room Upper Chest", LocationID::JabuJabusBellyMQSecondRoomUpperChest},
        {"Jabu Jabus Belly MQ Near Boss Chest", LocationID::JabuJabusBellyMQNearBossChest},
        {"Jabu Jabus Belly MQ Cow", LocationID::JabuJabusBellyMQCow},
        {"Jabu Jabus Belly MQ GS Boomerang Chest Room", LocationID::JabuJabusBellyMQGSBoomerangChestRoom},
        {"Jabu Jabus Belly MQ GS Tailpasaran Room", LocationID::JabuJabusBellyMQGSTailpasaranRoom},
        {"Jabu Jabus Belly MQ GS Invisible Enemies Room", LocationID::JabuJabusBellyMQGSInvisibleEnemiesRoom},
        {"Jabu Jabus Belly MQ GS Near Boss", LocationID::JabuJabusBellyMQGSNearBoss},
        {"Jabu Jabus Belly Barinade Heart", LocationID::JabuJabusBellyBarinadeHeart},
        {"Bottom of the Well Front Left Fake Wall Chest", LocationID::BottomoftheWellFrontLeftFakeWallChest},
        {"Bottom of the Well Front Center Bombable Chest", LocationID::BottomoftheWellFrontCenterBombableChest},
        {"Bottom of the Well Back Left Bombable Chest", LocationID::BottomoftheWellBackLeftBombableChest},
        {"Bottom of the Well Underwater Left Chest", LocationID::BottomoftheWellUnderwaterLeftChest},
        {"Bottom of the Well Freestanding Key", LocationID::BottomoftheWellFreestandingKey},
        {"Bottom of the Well Compass Chest", LocationID::BottomoftheWellCompassChest},
        {"Bottom of the Well Center Skulltula Chest", LocationID::BottomoftheWellCenterSkulltulaChest},
        {"Bottom of the Well Right Bottom Fake Wall Chest", LocationID::BottomoftheWellRightBottomFakeWallChest},
        {"Bottom of the Well Fire Keese Chest", LocationID::BottomoftheWellFireKeeseChest},
        {"Bottom of the Well Like Like Chest", LocationID::BottomoftheWellLikeLikeChest},
        {"Bottom of the Well Map Chest", LocationID::BottomoftheWellMapChest},
        {"Bottom of the Well Underwater Front Chest", LocationID::BottomoftheWellUnderwaterFrontChest},
        {"Bottom of the Well Invisible Chest", LocationID::BottomoftheWellInvisibleChest},
        {"Bottom of the Well Lens of Truth Chest", LocationID::BottomoftheWellLensofTruthChest},
        {"Bottom of the Well GS West Inner Room", LocationID::BottomoftheWellGSWestInnerRoom},
        {"Bottom of the Well GS East Inner Room", LocationID::BottomoftheWellGSEastInnerRoom},
        {"Bottom of the Well GS Like Like Cage", LocationID::BottomoftheWellGSLikeLikeCage},
        {"Bottom of the Well MQ Map Chest", LocationID::BottomoftheWellMQMapChest},
        {"Bottom of the Well MQ East Inner Room Freestanding Key", LocationID::BottomoftheWellMQEastInnerRoomFreestandingKey},
        {"Bottom of the Well MQ Compass Chest", LocationID::BottomoftheWellMQCompassChest},
        {"Bottom of the Well MQ Dead Hand Freestanding Key", LocationID::BottomoftheWellMQDeadHandFreestandingKey},
        {"Bottom of the Well MQ Lens of Truth Chest", LocationID::BottomoftheWellMQLensofTruthChest},
        {"Bottom of the Well MQ GS Coffin Room", LocationID::BottomoftheWellMQGSCoffinRoom},
        {"Bottom of the Well MQ GS West Inner Room", LocationID::BottomoftheWellMQGSWestInnerRoom},
        {"Bottom of the Well MQ GS Basement", LocationID::BottomoftheWellMQGSBasement},
        {"Forest Temple First Room Chest", LocationID::ForestTempleFirstRoomChest},
        {"Forest Temple First Stalfos Chest", LocationID::ForestTempleFirstStalfosChest},
        {"Forest Temple Raised Island Courtyard Chest", LocationID::ForestTempleRaisedIslandCourtyardChest},
        {"Forest Temple Map Chest", LocationID::ForestTempleMapChest},
        {"Forest Temple Well Chest", LocationID::ForestTempleWellChest},
        {"Forest Temple Eye Switch Chest", LocationID::ForestTempleEyeSwitchChest},
        {"Forest Temple Boss Key Chest", LocationID::ForestTempleBossKeyChest},
        {"Forest Temple Floormaster Chest", LocationID::ForestTempleFloormasterChest},
        {"Forest Temple Red Poe Chest", LocationID::ForestTempleRedPoeChest},
        {"Forest Temple Bow Chest", LocationID::ForestTempleBowChest},
        {"Forest Temple Blue Poe Chest", LocationID::ForestTempleBluePoeChest},
        {"Forest Temple Falling Ceiling Room Chest", LocationID::ForestTempleFallingCeilingRoomChest},
        {"Forest Temple Basement Chest", LocationID::ForestTempleBasementChest},
        {"Forest Temple GS First Room", LocationID::ForestTempleGSFirstRoom},
        {"Forest Temple GS Lobby", LocationID::ForestTempleGSLobby},
        {"Forest Temple GS Raised Island Courtyard", LocationID::ForestTempleGSRaisedIslandCourtyard},
        {"Forest Temple GS Level Island Courtyard", LocationID::ForestTempleGSLevelIslandCourtyard},
        {"Forest Temple GS Basement", LocationID::ForestTempleGSBasement},
        {"Forest Temple MQ First Room Chest", LocationID::ForestTempleMQFirstRoomChest},
        {"Forest Temple MQ Wolfos Chest", LocationID::ForestTempleMQWolfosChest},
        {"Forest Temple MQ Well Chest", LocationID::ForestTempleMQWellChest},
        {"Forest Temple MQ Raised Island Courtyard Lower Chest", LocationID::ForestTempleMQRaisedIslandCourtyardLowerChest},
        {"Forest Temple MQ Raised Island Courtyard Upper Chest", LocationID::ForestTempleMQRaisedIslandCourtyardUpperChest},
        {"Forest Temple MQ Boss Key Chest", LocationID::ForestTempleMQBossKeyChest},
        {"Forest Temple MQ Redead Chest", LocationID::ForestTempleMQRedeadChest},
        {"Forest Temple MQ Map Chest", LocationID::ForestTempleMQMapChest},
        {"Forest Temple MQ Bow Chest", LocationID::ForestTempleMQBowChest},
        {"Forest Temple MQ Compass Chest", LocationID::ForestTempleMQCompassChest},
        {"Forest Temple MQ Falling Ceiling Room Chest", LocationID::ForestTempleMQFallingCeilingRoomChest},
        {"Forest Temple MQ Basement Chest", LocationID::ForestTempleMQBasementChest},
        {"Forest Temple MQ GS First Hallway", LocationID::ForestTempleMQGSFirstHallway},
        {"Forest Temple MQ GS Raised Island Courtyard", LocationID::ForestTempleMQGSRaisedIslandCourtyard},
        {"Forest Temple MQ GS Level Island Courtyard", LocationID::ForestTempleMQGSLevelIslandCourtyard},
        {"Forest Temple MQ GS Well", LocationID::ForestTempleMQGSWell},
        {"Forest Temple MQ GS Block Push Room", LocationID::ForestTempleMQGSBlockPushRoom},
        {"Forest Temple Phantom Ganon Heart", LocationID::ForestTemplePhantomGanonHeart},
        {"Fire Temple Near Boss Chest", LocationID::FireTempleNearBossChest},
        {"Fire Temple Flare Dancer Chest", LocationID::FireTempleFlareDancerChest},
        {"Fire Temple Boss Key Chest", LocationID::FireTempleBossKeyChest},
        {"Fire Temple Big Lava Room Lower Open Door Chest", LocationID::FireTempleBigLavaRoomLowerOpenDoorChest},
        {"Fire Temple Big Lava Room Blocked Door Chest", LocationID::FireTempleBigLavaRoomBlockedDoorChest},
        {"Fire Temple Boulder Maze Lower Chest", LocationID::FireTempleBoulderMazeLowerChest},
        {"Fire Temple Boulder Maze Side Room Chest", LocationID::FireTempleBoulderMazeSideRoomChest},
        {"Fire Temple Map Chest", LocationID::FireTempleMapChest},
        {"Fire Temple Boulder Maze Shortcut Chest", LocationID::FireTempleBoulderMazeShortcutChest},
        {"Fire Temple Boulder Maze Upper Chest", LocationID::FireTempleBoulderMazeUpperChest},
        {"Fire Temple Scarecrow Chest", LocationID::FireTempleScarecrowChest},
        {"Fire Temple Compass Chest", LocationID::FireTempleCompassChest},
        {"Fire Temple Megaton Hammer Chest", LocationID::FireTempleMegatonHammerChest},
        {"Fire Temple Highest Goron Chest", LocationID::FireTempleHighestGoronChest},
        {"Fire Temple GS Boss Key Loop", LocationID::FireTempleGSBossKeyLoop},
        {"Fire Temple GS Song of Time Room", LocationID::FireTempleGSSongofTimeRoom},
        {"Fire Temple GS Boulder Maze", LocationID::FireTempleGSBoulderMaze},
        {"Fire Temple GS Scarecrow Climb", LocationID::FireTempleGSScarecrowClimb},
        {"Fire Temple GS Scarecrow Top", LocationID::FireTempleGSScarecrowTop},
        {"Fire Temple MQ Map Room Side Chest", LocationID::FireTempleMQMapRoomSideChest},
        {"Fire Temple MQ Megaton Hammer Chest", LocationID::FireTempleMQMegatonHammerChest},
        {"Fire Temple MQ Map Chest", LocationID::FireTempleMQMapChest},
        {"Fire Temple MQ Near Boss Chest", LocationID::FireTempleMQNearBossChest},
        {"Fire Temple MQ Big Lava Room Blocked Door Chest", LocationID::FireTempleMQBigLavaRoomBlockedDoorChest},
        {"Fire Temple MQ Boss Key Chest", LocationID::FireTempleMQBossKeyChest},
        {"Fire Temple MQ Lizalfos Maze Side Room Chest", LocationID::FireTempleMQLizalfosMazeSideRoomChest},
        {"Fire Temple MQ Compass Chest", LocationID::FireTempleMQCompassChest},
        {"Fire Temple MQ Lizalfos Maze Upper Chest", LocationID::FireTempleMQLizalfosMazeUpperChest},
        {"Fire Temple MQ Lizalfos Maze Lower Chest", LocationID::FireTempleMQLizalfosMazeLowerChest},
        {"Fire Temple MQ Freestanding Key", LocationID::FireTempleMQFreestandingKey},
        {"Fire Temple MQ Chest on Fire", LocationID::FireTempleMQChestOnFire},
        {"Fire Temple MQ GS Big Lava Room Open Door", LocationID::FireTempleMQGSBigLavaRoomOpenDoor},
        {"Fire Temple MQ GS Skull on Fire", LocationID::FireTempleMQGSSkullOnFire},
        {"Fire Temple MQ GS Fire Wall Maze Center", LocationID::FireTempleMQGSFireWallMazeCenter},
        {"Fire Temple MQ GS Fire Wall Maze Side Room", LocationID::FireTempleMQGSFireWallMazeSideRoom},
        {"Fire Temple MQ GS Above Fire Wall Maze", LocationID::FireTempleMQGSAboveFireWallMaze},
        {"Fire Temple Volvagia Heart", LocationID::FireTempleVolvagiaHeart},
        {"Water Temple Compass Chest", LocationID::WaterTempleCompassChest},
        {"Water Temple Map Chest", LocationID::WaterTempleMapChest},
        {"Water Temple Cracked Wall Chest", LocationID::WaterTempleCrackedWallChest},
        {"Water Temple Torches Chest", LocationID::WaterTempleTorchesChest},
        {"Water Temple Boss Key Chest", LocationID::WaterTempleBossKeyChest},
        {"Water Temple Central Pillar Chest", LocationID::WaterTempleCentralPillarChest},
        {"Water Temple Central Bow Target Chest", LocationID::WaterTempleCentralBowTargetChest},
        {"Water Temple Longshot Chest", LocationID::WaterTempleLongshotChest},
        {"Water Temple River Chest", LocationID::WaterTempleRiverChest},
        {"Water Temple Dragon Chest", LocationID::WaterTempleDragonChest},
        {"Water Temple GS Behind Gate", LocationID::WaterTempleGSBehindGate},
        {"Water Temple GS Near Boss Key Chest", LocationID::WaterTempleGSNearBossKeyChest},
        {"Water Temple GS Central Pillar", LocationID::WaterTempleGSCentralPillar},
        {"Water Temple GS Falling Platform Room", LocationID::WaterTempleGSFallingPlatformRoom},
        {"Water Temple GS River", LocationID::WaterTempleGSRiver},
        {"Water Temple MQ Longshot Chest", LocationID::WaterTempleMQLongshotChest},
        {"Water Temple MQ Map Chest", LocationID::WaterTempleMQMapChest},
        {"Water Temple MQ Compass Chest", LocationID::WaterTempleMQCompassChest},
        {"Water Temple MQ Central Pillar Chest", LocationID::WaterTempleMQCentralPillarChest},
        {"Water Temple MQ Boss Key Chest", LocationID::WaterTempleMQBossKeyChest},
        {"Water Temple MQ Freestanding Key", LocationID::WaterTempleMQFreestandingKey},
        {"Water Temple MQ GS Lizalfos Hallway", LocationID::WaterTempleMQGSLizalfosHallway},
        {"Water Temple MQ GS Before Upper Water Switch", LocationID::WaterTempleMQGSBeforeUpperWaterSwitch},
        {"Water Temple MQ GS River", LocationID::WaterTempleMQGSRiver},
        {"Water Temple MQ GS Freestanding Key Area", LocationID::WaterTempleMQGSFreestandingKeyArea},
        {"Water Temple MQ GS Triple Wall Torch", LocationID::WaterTempleMQGSTripleWallTorch},
        {"Water Temple Morpha Heart", LocationID::WaterTempleMorphaHeart},
        {"Shadow Temple Map Chest", LocationID::ShadowTempleMapChest},
        {"Shadow Temple Hover Boots Chest", LocationID::ShadowTempleHoverBootsChest},
        {"Shadow Temple Compass Chest", LocationID::ShadowTempleCompassChest},
        {"Shadow Temple Early Silver Rupee Chest", LocationID::ShadowTempleEarlySilverRupeeChest},
        {"Shadow Temple Invisible Blades Visible Chest", LocationID::ShadowTempleInvisibleBladesVisibleChest},
        {"Shadow Temple Invisible Blades Invisible Chest", LocationID::ShadowTempleInvisibleBladesInvisibleChest},
        {"Shadow Temple Falling Spikes Lower Chest", LocationID::ShadowTempleFallingSpikesLowerChest},
        {"Shadow Temple Falling Spikes Upper Chest", LocationID::ShadowTempleFallingSpikesUpperChest},
        {"Shadow Temple Falling Spikes Switch Chest", LocationID::ShadowTempleFallingSpikesSwitchChest},
        {"Shadow Temple Invisible Spikes Chest", LocationID::ShadowTempleInvisibleSpikesChest},
        {"Shadow Temple Freestanding Key", LocationID::ShadowTempleFreestandingKey},
        {"Shadow Temple Wind Hint Chest", LocationID::ShadowTempleWindHintChest},
        {"Shadow Temple After Wind Enemy Chest", LocationID::ShadowTempleAfterWindEnemyChest},
        {"Shadow Temple After Wind Hidden Chest", LocationID::ShadowTempleAfterWindHiddenChest},
        {"Shadow Temple Spike Walls Left Chest", LocationID::ShadowTempleSpikeWallsLeftChest},
        {"Shadow Temple Boss Key Chest", LocationID::ShadowTempleBossKeyChest},
        {"Shadow Temple Invisible Floormaster Chest", LocationID::ShadowTempleInvisibleFloormasterChest},
        {"Shadow Temple GS Like Like Room", LocationID::ShadowTempleGSLikeLikeRoom},
        {"Shadow Temple GS Falling Spikes Room", LocationID::ShadowTempleGSFallingSpikesRoom},
        {"Shadow Temple GS Single Giant Pot", LocationID::ShadowTempleGSSingleGiantPot},
        {"Shadow Temple GS Near Ship", LocationID::ShadowTempleGSNearShip},
        {"Shadow Temple GS Triple Giant Pot", LocationID::ShadowTempleGSTripleGiantPot},
        {"Shadow Temple MQ Early Gibdos Chest", LocationID::ShadowTempleMQEarlyGibdosChest},
        {"Shadow Temple MQ Map Chest", LocationID::ShadowTempleMQMapChest},
        {"Shadow Temple MQ Near Ship Invisible Chest", LocationID::ShadowTempleMQNearShipInvisibleChest},
        {"Shadow Temple MQ Compass Chest", LocationID::ShadowTempleMQCompassChest},
        {"Shadow Temple MQ Hover Boots Chest", LocationID::ShadowTempleMQHoverBootsChest},
        {"Shadow Temple MQ Invisible Blades Invisible Chest", LocationID::ShadowTempleMQInvisibleBladesInvisibleChest},
        {"Shadow Temple MQ Invisible Blades Visible Chest", LocationID::ShadowTempleMQInvisibleBladesVisibleChest},
        {"Shadow Temple MQ Beamos Silver Rupees Chest", LocationID::ShadowTempleMQBeamosSilverRupeesChest},
        {"Shadow Temple MQ Falling Spikes Lower Chest", LocationID::ShadowTempleMQFallingSpikesLowerChest},
        {"Shadow Temple MQ Falling Spikes Upper Chest", LocationID::ShadowTempleMQFallingSpikesUpperChest},
        {"Shadow Temple MQ Falling Spikes Switch Chest", LocationID::ShadowTempleMQFallingSpikesSwitchChest},
        {"Shadow Temple MQ Invisible Spikes Chest", LocationID::ShadowTempleMQInvisibleSpikesChest},
        {"Shadow Temple MQ Stalfos Room Chest", LocationID::ShadowTempleMQStalfosRoomChest},
        {"Shadow Temple MQ Wind Hint Chest", LocationID::ShadowTempleMQWindHintChest},
        {"Shadow Temple MQ After Wind Hidden Chest", LocationID::ShadowTempleMQAfterWindHiddenChest},
        {"Shadow Temple MQ After Wind Enemy Chest", LocationID::ShadowTempleMQAfterWindEnemyChest},
        {"Shadow Temple MQ Boss Key Chest", LocationID::ShadowTempleMQBossKeyChest},
        {"Shadow Temple MQ Spike Walls Left Chest", LocationID::ShadowTempleMQSpikeWallsLeftChest},
        {"Shadow Temple MQ Freestanding Key", LocationID::ShadowTempleMQFreestandingKey},
        {"Shadow Temple MQ Bomb Flower Chest", LocationID::ShadowTempleMQBombFlowerChest},
        {"Shadow Temple MQ GS Falling Spikes Room", LocationID::ShadowTempleMQGSFallingSpikesRoom},
        {"Shadow Temple MQ GS Wind Hint Room", LocationID::ShadowTempleMQGSWindHintRoom},
        {"Shadow Temple MQ GS After Wind", LocationID::ShadowTempleMQGSAfterWind},
        {"Shadow Temple MQ GS After Ship", LocationID::ShadowTempleMQGSAfterShip},
        {"Shadow Temple MQ GS Near Boss", LocationID::ShadowTempleMQGSNearBoss},
        {"Shadow Temple Bongo Bongo Heart", LocationID::ShadowTempleBongoBongoHeart},
        {"Spirit Temple Child Bridge Chest", LocationID::SpiritTempleChildBridgeChest},
        {"Spirit Temple Child Early Torches Chest", LocationID::SpiritTempleChildEarlyTorchesChest},
        {"Spirit Temple Child Climb North Chest", LocationID::SpiritTempleChildClimbNorthChest},
        {"Spirit Temple Child Climb East Chest", LocationID::SpiritTempleChildClimbEastChest},
        {"Spirit Temple Map Chest", LocationID::SpiritTempleMapChest},
        {"Spirit Temple Sun Block Room Chest", LocationID::SpiritTempleSunBlockRoomChest},
        {"Spirit Temple MQ Entrance Front Left Chest", LocationID::SpiritTempleMQEntranceFrontLeftChest},
        {"Spirit Temple MQ Entrance Back Right Chest", LocationID::SpiritTempleMQEntranceBackRightChest},
        {"Spirit Temple MQ Entrance Front Right Chest", LocationID::SpiritTempleMQEntranceFrontRightChest},
        {"Spirit Temple MQ Entrance Back Left Chest", LocationID::SpiritTempleMQEntranceBackLeftChest},
        {"Spirit Temple MQ Map Chest", LocationID::SpiritTempleMQMapChest},
        {"Spirit Temple MQ Map Room Enemy Chest", LocationID::SpiritTempleMQMapRoomEnemyChest},
        {"Spirit Temple MQ Child Climb North Chest", LocationID::SpiritTempleMQChildClimbNorthChest},
        {"Spirit Temple MQ Child Climb South Chest", LocationID::SpiritTempleMQChildClimbSouthChest},
        {"Spirit Temple MQ Compass Chest", LocationID::SpiritTempleMQCompassChest},
        {"Spirit Temple MQ Silver Block Hallway Chest", LocationID::SpiritTempleMQSilverBlockHallwayChest},
        {"Spirit Temple MQ Sun Block Room Chest", LocationID::SpiritTempleMQSunBlockRoomChest},
        {"Spirit Temple Silver Gauntlets Chest", LocationID::SpiritTempleSilverGauntletsChest},
        {"Spirit Temple Compass Chest", LocationID::SpiritTempleCompassChest},
        {"Spirit Temple Early Adult Right Chest", LocationID::SpiritTempleEarlyAdultRightChest},
        {"Spirit Temple First Mirror Left Chest", LocationID::SpiritTempleFirstMirrorLeftChest},
        {"Spirit Temple First Mirror Right Chest", LocationID::SpiritTempleFirstMirrorRightChest},
        {"Spirit Temple Statue Room Northeast Chest", LocationID::SpiritTempleStatueRoomNortheastChest},
        {"Spirit Temple Statue Room Hand Chest", LocationID::SpiritTempleStatueRoomHandChest},
        {"Spirit Temple Near Four Armos Chest", LocationID::SpiritTempleNearFourArmosChest},
        {"Spirit Temple Hallway Right Invisible Chest", LocationID::SpiritTempleHallwayRightInvisibleChest},
        {"Spirit Temple Hallway Left Invisible Chest", LocationID::SpiritTempleHallwayLeftInvisibleChest},
        {"Spirit Temple MQ Child Hammer Switch Chest", LocationID::SpiritTempleMQChildHammerSwitchChest},
        {"Spirit Temple MQ Statue Room Lullaby Chest", LocationID::SpiritTempleMQStatueRoomLullabyChest},
        {"Spirit Temple MQ Statue Room Invisible Chest", LocationID::SpiritTempleMQStatueRoomInvisibleChest},
        {"Spirit Temple MQ Leever Room Chest", LocationID::SpiritTempleMQLeeverRoomChest},
        {"Spirit Temple MQ Symphony Room Chest", LocationID::SpiritTempleMQSymphonyRoomChest},
        {"Spirit Temple MQ Beamos Room Chest", LocationID::SpiritTempleMQBeamosRoomChest},
        {"Spirit Temple MQ Chest Switch Chest", LocationID::SpiritTempleMQChestSwitchChest},
        {"Spirit Temple MQ Boss Key Chest", LocationID::SpiritTempleMQBossKeyChest},
        {"Spirit Temple Mirror Shield Chest", LocationID::SpiritTempleMirrorShieldChest},
        {"Spirit Temple Boss Key Chest", LocationID::SpiritTempleBossKeyChest},
        {"Spirit Temple Topmost Chest", LocationID::SpiritTempleTopmostChest},
        {"Spirit Temple MQ Mirror Puzzle Invisible Chest", LocationID::SpiritTempleMQMirrorPuzzleInvisibleChest},
        {"Spirit Temple GS Metal Fence", LocationID::SpiritTempleGSMetalFence},
        {"Spirit Temple GS Sun on Floor Room", LocationID::SpiritTempleGSSunonFloorRoom},
        {"Spirit Temple GS Hall After Sun Block Room", LocationID::SpiritTempleGSHallAfterSunBlockRoom},
        {"Spirit Temple GS Lobby", LocationID::SpiritTempleGSLobby},
        {"Spirit Temple GS Boulder Room", LocationID::SpiritTempleGSBoulderRoom},
        {"Spirit Temple MQ GS Sun Block Room", LocationID::SpiritTempleMQGSSunBlockRoom},
        {"Spirit Temple MQ GS Leever Room", LocationID::SpiritTempleMQGSLeeverRoom},
        {"Spirit Temple MQ GS Symphony Room", LocationID::SpiritTempleMQGSSymphonyRoom},
        {"Spirit Temple MQ GS Nine Thrones Room West", LocationID::SpiritTempleMQGSNineThronesRoomWest},
        {"Spirit Temple MQ GS Nine Thrones Room North", LocationID::SpiritTempleMQGSNineThronesRoomNorth},
        {"Spirit Temple Twinrova Heart", LocationID::SpiritTempleTwinrovaHeart},
        {"Ice Cavern Map Chest", LocationID::IceCavernMapChest},
        {"Ice Cavern Compass Chest", LocationID::IceCavernCompassChest},
        {"Ice Cavern Freestanding PoH" , LocationID::IceCavernFreestandingPoH},
        {"Ice Cavern Iron Boots Chest", LocationID::IceCavernIronBootsChest},
        {"Ice Cavern GS Spinning Scythe Room", LocationID::IceCavernGSSpinningScytheRoom},
        {"Ice Cavern GS Heart Piece Room", LocationID::IceCavernGSHeartPieceRoom},
        {"Ice Cavern GS Push Block Room", LocationID::IceCavernGSPushBlockRoom},
        {"Ice Cavern MQ Map Chest", LocationID::IceCavernMQMapChest},
        {"Ice Cavern MQ Compass Chest", LocationID::IceCavernMQCompassChest},
        {"Ice Cavern MQ Freestanding PoH" , LocationID::IceCavernMQFreestandingPoH},
        {"Ice Cavern MQ Iron Boots Chest", LocationID::IceCavernMQIronBootsChest},
        {"Ice Cavern MQ GS Red Ice", LocationID::IceCavernMQGSRedIce},
        {"Ice Cavern MQ GS Ice Block", LocationID::IceCavernMQGSIceBlock},
        {"Ice Cavern MQ GS Scarecrow", LocationID::IceCavernMQGSScarecrow},
        {"Gerudo Training Ground Lobby Left Chest", LocationID::GerudoTrainingGroundLobbyLeftChest},
        {"Gerudo Training Ground Lobby Right Chest", LocationID::GerudoTrainingGroundLobbyRightChest},
        {"Gerudo Training Ground Stalfos Chest", LocationID::GerudoTrainingGroundStalfosChest},
        {"Gerudo Training Ground Before Heavy Block Chest", LocationID::GerudoTrainingGroundBeforeHeavyBlockChest},
        {"Gerudo Training Ground Heavy Block First Chest", LocationID::GerudoTrainingGroundHeavyBlockFirstChest},
        {"Gerudo Training Ground Heavy Block Second Chest", LocationID::GerudoTrainingGroundHeavyBlockSecondChest},
        {"Gerudo Training Ground Heavy Block Third Chest", LocationID::GerudoTrainingGroundHeavyBlockThirdChest},
        {"Gerudo Training Ground Heavy Block Fourth Chest", LocationID::GerudoTrainingGroundHeavyBlockFourthChest},
        {"Gerudo Training Ground Eye Statue Chest", LocationID::GerudoTrainingGroundEyeStatueChest},
        {"Gerudo Training Ground Near Scarecrow Chest", LocationID::GerudoTrainingGroundNearScarecrowChest},
        {"Gerudo Training Ground Hammer Room Clear Chest", LocationID::GerudoTrainingGroundHammerRoomClearChest},
        {"Gerudo Training Ground Hammer Room Switch Chest", LocationID::GerudoTrainingGroundHammerRoomSwitchChest},
        {"Gerudo Training Ground Freestanding Key", LocationID::GerudoTrainingGroundFreestandingKey},
        {"Gerudo Training Ground Maze Right Central Chest", LocationID::GerudoTrainingGroundMazeRightCentralChest},
        {"Gerudo Training Ground Maze Right Side Chest", LocationID::GerudoTrainingGroundMazeRightSideChest},
        {"Gerudo Training Ground Underwater Silver Rupee Chest", LocationID::GerudoTrainingGroundUnderwaterSilverRupeeChest},
        {"Gerudo Training Ground Beamos Chest", LocationID::GerudoTrainingGroundBeamosChest},
        {"Gerudo Training Ground Hidden Ceiling Chest", LocationID::GerudoTrainingGroundHiddenCeilingChest},
        {"Gerudo Training Ground Maze Path First Chest", LocationID::GerudoTrainingGroundMazePathFirstChest},
        {"Gerudo Training Ground Maze Path Second Chest", LocationID::GerudoTrainingGroundMazePathSecondChest},
        {"Gerudo Training Ground Maze Path Third Chest", LocationID::GerudoTrainingGroundMazePathThirdChest},
        {"Gerudo Training Ground Maze Path Final Chest", LocationID::GerudoTrainingGroundMazePathFinalChest},
        {"Gerudo Training Ground MQ Lobby Left Chest", LocationID::GerudoTrainingGroundMQLobbyLeftChest},
        {"Gerudo Training Ground MQ Lobby Right Chest", LocationID::GerudoTrainingGroundMQLobbyRightChest},
        {"Gerudo Training Ground MQ First Iron Knuckle Chest", LocationID::GerudoTrainingGroundMQFirstIronKnuckleChest},
        {"Gerudo Training Ground MQ Before Heavy Block Chest", LocationID::GerudoTrainingGroundMQBeforeHeavyBlockChest},
        {"Gerudo Training Ground MQ Heavy Block Chest", LocationID::GerudoTrainingGroundMQHeavyBlockChest},
        {"Gerudo Training Ground MQ Eye Statue Chest", LocationID::GerudoTrainingGroundMQEyeStatueChest},
        {"Gerudo Training Ground MQ Ice Arrows Chest", LocationID::GerudoTrainingGroundMQIceArrowsChest},
        {"Gerudo Training Ground MQ Second Iron Knuckle Chest", LocationID::GerudoTrainingGroundMQSecondIronKnuckleChest},
        {"Gerudo Training Ground MQ Flame Circle Chest", LocationID::GerudoTrainingGroundMQFlameCircleChest},
        {"Gerudo Training Ground MQ Maze Right Central Chest", LocationID::GerudoTrainingGroundMQMazeRightCentralChest},
        {"Gerudo Training Ground MQ Maze Right Side Chest", LocationID::GerudoTrainingGroundMQMazeRightSideChest},
        {"Gerudo Training Ground MQ Underwater Silver Rupee Chest", LocationID::GerudoTrainingGroundMQUnderwaterSilverRupeeChest},
        {"Gerudo Training Ground MQ Dinolfos Chest", LocationID::GerudoTrainingGroundMQDinolfosChest},
        {"Gerudo Training Ground MQ Hidden Ceiling Chest", LocationID::GerudoTrainingGroundMQHiddenCeilingChest},
        {"Gerudo Training Ground MQ Maze Path First Chest", LocationID::GerudoTrainingGroundMQMazePathFirstChest},
        {"Gerudo Training Ground MQ Maze Path Third Chest", LocationID::GerudoTrainingGroundMQMazePathThirdChest},
        {"Gerudo Training Ground MQ Maze Path Second Chest", LocationID::GerudoTrainingGroundMQMazePathSecondChest},
        {"Ganons Castle Forest Trial Chest", LocationID::GanonsCastleForestTrialChest},
        {"Ganons Castle Water Trial Left Chest", LocationID::GanonsCastleWaterTrialLeftChest},
        {"Ganons Castle Water Trial Right Chest", LocationID::GanonsCastleWaterTrialRightChest},
        {"Ganons Castle Shadow Trial Front Chest", LocationID::GanonsCastleShadowTrialFrontChest},
        {"Ganons Castle Shadow Trial Golden Gauntlets Chest", LocationID::GanonsCastleShadowTrialGoldenGauntletsChest},
        {"Ganons Castle Light Trial First Left Chest", LocationID::GanonsCastleLightTrialFirstLeftChest},
        {"Ganons Castle Light Trial Second Left Chest", LocationID::GanonsCastleLightTrialSecondLeftChest},
        {"Ganons Castle Light Trial Third Left Chest", LocationID::GanonsCastleLightTrialThirdLeftChest},
        {"Ganons Castle Light Trial First Right Chest", LocationID::GanonsCastleLightTrialFirstRightChest},
        {"Ganons Castle Light Trial Second Right Chest", LocationID::GanonsCastleLightTrialSecondRightChest},
        {"Ganons Castle Light Trial Third Right Chest", LocationID::GanonsCastleLightTrialThirdRightChest},
        {"Ganons Castle Light Trial Invisible Enemies Chest", LocationID::GanonsCastleLightTrialInvisibleEnemiesChest},
        {"Ganons Castle Light Trial Lullaby Chest", LocationID::GanonsCastleLightTrialLullabyChest},
        {"Ganons Castle Spirit Trial Crystal Switch Chest", LocationID::GanonsCastleSpiritTrialCrystalSwitchChest},
        {"Ganons Castle Spirit Trial Invisible Chest", LocationID::GanonsCastleSpiritTrialInvisibleChest},
        {"Ganons Castle Deku Scrub Left", LocationID::GanonsCastleDekuScrubLeft},
        {"Ganons Castle Deku Scrub Center Left", LocationID::GanonsCastleDekuScrubCenterLeft},
        {"Ganons Castle Deku Scrub Center Right", LocationID::GanonsCastleDekuScrubCenterRight},
        {"Ganons Castle Deku Scrub Right", LocationID::GanonsCastleDekuScrubRight},
        {"Ganons Castle MQ Forest Trial Freestanding Key", LocationID::GanonsCastleMQForestTrialFreestandingKey},
        {"Ganons Castle MQ Forest Trial Eye Switch Chest", LocationID::GanonsCastleMQForestTrialEyeSwitchChest},
        {"Ganons Castle MQ Forest Trial Frozen Eye Switch Chest", LocationID::GanonsCastleMQForestTrialFrozenEyeSwitchChest},
        {"Ganons Castle MQ Water Trial Chest", LocationID::GanonsCastleMQWaterTrialChest},
        {"Ganons Castle MQ Shadow Trial Bomb Flower Chest", LocationID::GanonsCastleMQShadowTrialBombFlowerChest},
        {"Ganons Castle MQ Shadow Trial Eye Switch Chest", LocationID::GanonsCastleMQShadowTrialEyeSwitchChest},
        {"Ganons Castle MQ Light Trial Lullaby Chest", LocationID::GanonsCastleMQLightTrialLullabyChest},
        {"Ganons Castle MQ Spirit Trial First Chest", LocationID::GanonsCastleMQSpiritTrialFirstChest},
        {"Ganons Castle MQ Spirit Trial Invisible Chest", LocationID::GanonsCastleMQSpiritTrialInvisibleChest},
        {"Ganons Castle MQ Spirit Trial Sun Front Left Chest", LocationID::GanonsCastleMQSpiritTrialSunFrontLeftChest},
        {"Ganons Castle MQ Spirit Trial Sun Back Left Chest", LocationID::GanonsCastleMQSpiritTrialSunBackLeftChest},
        {"Ganons Castle MQ Spirit Trial Sun Back Right Chest", LocationID::GanonsCastleMQSpiritTrialSunBackRightChest},
        {"Ganons Castle MQ Spirit Trial Golden Gauntlets Chest", LocationID::GanonsCastleMQSpiritTrialGoldenGauntletsChest},
        {"Ganons Castle MQ Deku Scrub Left", LocationID::GanonsCastleMQDekuScrubLeft},
        {"Ganons Castle MQ Deku Scrub Center Left", LocationID::GanonsCastleMQDekuScrubCenterLeft},
        {"Ganons Castle MQ Deku Scrub Center", LocationID::GanonsCastleMQDekuScrubCenter},
        {"Ganons Castle MQ Deku Scrub Center Right", LocationID::GanonsCastleMQDekuScrubCenterRight},
        {"Ganons Castle MQ Deku Scrub Right", LocationID::GanonsCastleMQDekuScrubRight},
        {"Ganons Tower Boss Key Chest", LocationID::GanonsTowerBossKeyChest},
        {"Pierre", LocationID::Pierre},
        {"Deliver Rutos Letter", LocationID::DeliverRutosLetter},
        {"Master Sword Pedestal", LocationID::MasterSwordPedestal},
        {"Deku BabaS ticks", LocationID::DekuBabaSticks},
        {"Deku Baba Nuts", LocationID::DekuBabaNuts},
        {"Stick Pot", LocationID::StickPot},
        {"Nut Pot", LocationID::NutPot},
        {"Nut Crate", LocationID::NutCrate},
        {"Blue Fire", LocationID::BlueFire},
        {"Lone Fish", LocationID::LoneFish},
        {"Fish Group", LocationID::FishGroup},
        {"Bug Rock", LocationID::BugRock},
        {"BugShrub", LocationID::BugShrub},
        {"WanderingBugs", LocationID::WanderingBugs},
        {"FairyPot", LocationID::FairyPot},
        {"FreeFairies", LocationID::FreeFairies},
        {"WallFairy", LocationID::WallFairy},
        {"ButterflyFairy", LocationID::ButterflyFairy},
        {"GossipStoneFairy", LocationID::GossipStoneFairy},
        {"BeanPlantFairy", LocationID::BeanPlantFairy},
        {"FairyPond", LocationID::FairyPond},
        {"BigPoeKill", LocationID::BigPoeKill},
        {"DMCGossipStone", LocationID::DMCGossipStone},
        {"DMTGossipStone", LocationID::DMTGossipStone},
        {"ColossusGossipStone", LocationID::ColossusGossipStone},
        {"DodongosCavernGossipStone", LocationID::DodongosCavernGossipStone},
        {"GVGossipStone", LocationID::GVGossipStone},
        {"GCMazeGossipStone", LocationID::GCMazeGossipStone},
        {"GCMedigoronGossipStone", LocationID::GCMedigoronGossipStone},
        {"GraveyardGossipStone", LocationID::GraveyardGossipStone},
        {"HCMalonGossipStone", LocationID::HCMalonGossipStone},
        {"HCRockWallGossipStone", LocationID::HCRockWallGossipStone},
        {"HCStormsGrottoGossipStone", LocationID::HCStormsGrottoGossipStone},
        {"HF CowGrottoGossipStone", LocationID::HFCowGrottoGossipStone},
        {"KF DekuTreeGossipStoneLeft", LocationID::KFDekuTreeGossipStoneLeft},
        {"KF DekuTreeGossipStoneRight", LocationID::KFDekuTreeGossipStoneRight},
        {"KF GossipStone", LocationID::KFGossipStone},
        {"LHLabGossipStone", LocationID::LHLabGossipStone},
        {"LHGossipStoneSoutheast", LocationID::LHGossipStoneSoutheast},
        {"LHGossipStoneSouthwest", LocationID::LHGossipStoneSouthwest},
        {"LW GossipStone", LocationID::LWGossipStone},
        {"SFMMazeGossipStoneLower", LocationID::SFMMazeGossipStoneLower},
        {"SFMMazeGossipStoneUpper", LocationID::SFMMazeGossipStoneUpper},
        {"SFMSariaGossipStone", LocationID::SFMSariaGossipStone},
        {"ToTGossipStoneLeft", LocationID::ToTGossipStoneLeft},
        {"ToTGossipStoneLeftCenter", LocationID::ToTGossipStoneLeftCenter},
        {"ToTGossipStoneRight", LocationID::ToTGossipStoneRight},
        {"ToTGossipStoneRightCenter", LocationID::ToTGossipStoneRightCenter},
        {"ZDGossipStone", LocationID::ZDGossipStone},
        {"ZFFairyGossipStone", LocationID::ZFFairyGossipStone},
        {"ZFJabuGossipStone", LocationID::ZFJabuGossipStone},
        {"ZRNearGrottosGossipStone", LocationID::ZRNearGrottosGossipStone},
        {"ZRNearDomainGossipStone", LocationID::ZRNearDomainGossipStone},
        {"HF NearMarketGrottoGossipStone", LocationID::HFNearMarketGrottoGossipStone},
        {"HF SoutheastGrottoGossipStone", LocationID::HFSoutheastGrottoGossipStone},
        {"HF OpenGrottoGossipStone", LocationID::HFOpenGrottoGossipStone},
        {"Kak OpenGrottoGossipStone", LocationID::KakOpenGrottoGossipStone},
        {"ZROpenGrottoGossipStone", LocationID::ZROpenGrottoGossipStone},
        {"KF StormsGrottoGossipStone", LocationID::KFStormsGrottoGossipStone},
        {"LW NearShortcutsGrottoGossipStone", LocationID::LWNearShortcutsGrottoGossipStone},
        {"DMTStormsGrottoGossipStone", LocationID::DMTStormsGrottoGossipStone},
        {"DMCUpperGrottoGossipStone", LocationID::DMCUpperGrottoGossipStone},
        {"GanondorfHint", LocationID::GanondorfHint},
    };

    if (nameLocationMap.count(name) == 0)
    {
        return LocationID::INVALID;
    }
    return nameLocationMap.at(name);
}

Location::Location(const LocationID& id_, std::string name_, World* world_, Area* area_) :
                      id(id_), name(std::move(name_)), world(world_), area(area_) {}

Location::~Location() = default;

LocationID Location::GetID() const
{
    return id;
}

std::string Location::GetName() const
{
    return name;
}

World* Location::GetWorld() const
{
    return world;
}

Area* Location::GetArea() const
{
    return area;
}

Item Location::GetCurrentItem() const
{
    return currentItem;
}
